stages:
  - build
  - unit_tests
  - api_tests
  - perf_tests

build:
  stage: build
  tags:
    - gc
  variables:
    MPI_HOME: "/opt/mpi/openmpi-1.10.7"
    CUDA_HOME: "/usr/local/cuda-11.0"
  script:
    - make -j test.build MPI=1 MPI_HOME=$MPI_HOME CUDA_HOME=$CUDA_HOME
  artifacts:
    paths:
      - build

unit_tests:
  stage: unit_tests
  tags:
    - gc
  variables:
    CUDA_HOME: "/usr/local/cuda-11.0"
  script:
    - (cd build/test/unit; LD_LIBRARY_PATH=$PWD/../../lib:$CUDA_HOME/lib64 ./graph_test)

apitest-P100:
  stage: api_tests
  tags:
    - gc
  variables:
    CUDA_HOME: "/usr/local/cuda-11.0"
    SRUN: "srun -n 1 -c 8 -pP100"
  script:
    - ./test/scripts/gitlab-runner-apitest.sh

apitest-P40:
  stage: api_tests
  tags:
    - gc
  variables:
    CUDA_HOME: "/usr/local/cuda-11.0"
    SRUN: "srun -n 1 -c 8 -pP40"
  script:
    - ./test/scripts/gitlab-runner-apitest.sh

apitest-DGX1V:
  stage: api_tests
  tags:
    - dgx-1v
  variables:
    CUDA_HOME: "$HOME/prom-dev/cuda-11.0"
    SRUN: "srun -n 1 --account=sw-gpu -pbatch -t 00:05:00"
  script:
    - ./test/scripts/gitlab-runner-apitest.sh

perftest-P100:
  stage: perf_tests
  tags:
    - gc
  variables:
    MPI_HOME: "/opt/mpi/openmpi-1.10.7"
    CUDA_HOME: "/usr/local/cuda-11.0"
    SALLOC: "salloc -n 8 -pP100"
  script:
    - ./test/scripts/gitlab-runner-perftest.sh

perftest-P40:
  stage: perf_tests
  tags:
    - gc
  variables:
    MPI_HOME: "/opt/mpi/openmpi-1.10.7"
    CUDA_HOME: "/usr/local/cuda-11.0"
    SALLOC: "salloc -n 8 -pP40"
  script:
    - ./test/scripts/gitlab-runner-perftest.sh

perftest-DGX1V:
  stage: perf_tests
  tags:
    - dgx-1v
  variables:
    MPI_HOME: "$HOME/prom-dev/mpi/openmpi-1.10.7"
    CUDA_HOME: "$HOME/prom-dev/cuda-11.0"
    SALLOC: "salloc -n 32 --account=sw-gpu -pbatch -t 00:05:00"
  script:
    - ./test/scripts/gitlab-runner-perftest.sh

