stages:
  - build
  - setup
  - health
  - unit_tests
  - api_tests
  - perf_tests_single
  - perf_tests_multi
  - perf_regression
  - profiler_tests
  - replay_tests
  - summary

variables:
  RUN_MULTI_REGRESSION: "0" # Set to 1 to run multinode regression pipeline
  MULTI_PERFTEST_NODE_COUNT: 4
  CUDA_VERSION: "11.7"
  REGRESSION_BASELINE: "v2.15.5-1" # Compare to stable branch (Update git tag as necessary)
  REGRESSION_THRESHOLD: 7 # What percent difference should we use to compare?
  REGRESSION_ITERATIONS: 5 # How many iterations should we run latency and overhead tests?
  REGRESSION_CHECK_CPU_OVERHEAD: 0 # Should we run CPU overhead tests in the perf regression?
  MULTI_REGRESSION_SALLOC_TIME: 45 # How many minutes to salloc for multinode regression. This can be tuned for multinode pipelines
  SINGLE_REGRESSION_SALLOC_TIME: 30 # How many minutes to salloc for multinode regression. This can be tuned for multinode pipelines
  SHARP_MULTI_JOB_TIME:  10
  RUN_ON_SELENE_SHARP: "0"
  BUILD_TRACE: "0"
  RUN_ON_AWS: "1"
  RUN_ON_EOS: "1"
  RUN_ON_DRACO_OCI: "1"
  RUN_ON_PRE_NYX: "1"
  RUN_ON_PRE_TYCHE: "1"
  RUN_UNIT_API_TESTS_ON_DRACO_OCI: "0" # TODO (kartiki/bewilliams) - Enable after addressing https://nvbugspro.nvidia.com/bug/4861033
  PLANNED_RESERVED: "Reserved"
  RUN_DLFW_TESTS: "1"

default:
  # set all jobs to interruptible by default
  interruptible: true

# Run our CI on:
# - Every commit to master
# - Every commit to a merge request
# - Schedules (nightlies and weeklies)
# - Merge requests without "Draft:" in the title
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_TITLE !~ /^Draft:/ && ($CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_PIPELINE_SOURCE == 'schedule' || $CI_PIPELINE_SOURCE == 'web' || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "next" || $CI_COMMIT_BRANCH == "stable" || $CI_COMMIT_BRANCH == $NCCL_RELEASE_BRANCH)
  # when cancelling a redundant pipeline, cancel all jobs that are interruptible
  auto_cancel:
    on_new_commit: interruptible

build-trace:
  stage: build
  rules:
    - if: $BUILD_TRACE == "1" || $CI_PIPELINE_SOURCE == 'schedule'
      when: always
    - when: never
  tags:
    - build
  variables:
    MPI_HOME: "/opt/mpi/openmpi-1.10.7"
    CUDA_HOME: "/usr/local/cuda-${CUDA_VERSION}"
  script:
    - echo "Using CUDA_HOME=$CUDA_HOME, MPI_HOME=$MPI_HOME"
    - make -j test.build MPI=1 TRACE=1 MPI_HOME=$MPI_HOME CUDA_HOME=$CUDA_HOME

build-classic:
  stage: build
  tags:
    - build-with-docker
  script:
    - docker/make.sh gc-classic
    - mv build build-gc
  artifacts:
    paths:
      - build-gc
    exclude:
      - build-gc/**/*.o
    expire_in: 48 hrs

build-eos-aws-oci:
  stage: build
  rules:
    - if: $RUN_ON_EOS == "1" || $RUN_ON_AWS == "1" || $RUN_ON_DRACO_OCI == "1"
      when: always
    - when: never
  tags:
    - build-with-docker
  script:
    - docker/make.sh draco-oci,eos
    - mv build build-eos
  artifacts:
    paths:
      - build-eos
    exclude:
      - build-eos/**/*.o
    expire_in: 48 hrs

build-pre-nyx:
  stage: build
  rules:
    - if: $RUN_ON_PRE_NYX == "1"
      when: always
    - when: never
  tags:
    - prenyx
  variables:
    CI_BUILDS_DIR: "/lustre/fsw/coreai_libraries_nccl/$GITLAB_USER_LOGIN/gitlab-runner"
  script:
    - docker/make.sh pre-nyx --clean --baremetal-build
    - mv build build-pre-nyx
  artifacts:
    paths:
      - build-pre-nyx
    exclude:
      - build-pre-nyx/**/*.o
    expire_in: 48 hrs

build-pre-tyche:
  stage: build
  rules:
    - if: $RUN_ON_PRE_TYCHE == "1"
      when: always
    - when: never
  tags:
    - ptyche
  variables:
    CI_BUILDS_DIR: "/lustre/fsw/coreai_libraries_nccl/$GITLAB_USER_LOGIN/gitlab-runner"
  script:
    - docker/make.sh pre-tyche
    - mv build build-pre-tyche
  artifacts:
    paths:
      - build-pre-tyche
    exclude:
      - build-pre-tyche/**/*.o
    expire_in: 48 hrs

build-dlfw-pytorch-container:
  stage: build
  rules:
    - if: $RUN_DLFW_TESTS == "1"
      when: always
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_PIPELINE_SOURCE == 'web'
      when: manual
    - when: never
  tags:
    - build-with-docker
  variables:
    CONTAINER: gitlab-master.nvidia.com/dl/dgx/pytorch:main-py3-devel
  script:
    - chmod +x test/scripts/dlfw/*.sh
    - ./test/scripts/dlfw/host_login_cr.sh
    - ./test/scripts/dlfw/host_build_nccl_pytorch.sh
  artifacts:
    paths:
      - build-dlfw
    expire_in: 48 hrs
  allow_failure: false

fairshare-eos:
  stage: setup
  rules:
    - if: $RUN_ON_EOS == "1"
      when: always
    - when: never
  needs: []
  variables:
    CI_BUILDS_DIR: "/lustre/fsw/coreai_libraries_nccl/$GITLAB_USER_LOGIN/gitlab-runner"
  tags:
    - nccl-eos
  script:
    - ./test/scripts/gitlab-runner-fairshare.sh

fairshare-draco-oci:
  stage: setup
  rules:
    - if: $RUN_ON_DRACO_OCI == "1"
      when: always
    - when: never
  needs: []
  tags:
    - draco-oci-iad
  script:
    - ./test/scripts/gitlab-runner-fairshare.sh

fairshare-pre-nyx:
  stage: setup
  rules:
    - if: $RUN_ON_PRE_NYX == "1"
      when: always
    - when: never
  needs: []
  variables:
    CI_BUILDS_DIR: "/lustre/fsw/coreai_libraries_nccl/$GITLAB_USER_LOGIN/gitlab-runner"
  tags:
    - prenyx
  script:
    - ./test/scripts/gitlab-runner-fairshare.sh

fairshare-pre-tyche:
  stage: setup
  rules:
    - if: $RUN_ON_PRE_TYCHE == "1"
      when: always
    - when: never
  needs: []
  variables:
    CI_BUILDS_DIR: "/lustre/fsw/coreai_libraries_nccl/$GITLAB_USER_LOGIN/gitlab-runner"
  tags:
    - ptyche
  script:
    - ./test/scripts/gitlab-runner-fairshare.sh

setup-AWS_H100_EFA:
  stage: setup
  rules:
    - if: $RUN_ON_AWS == "1"
      when: always
    - when: never
  tags:
    - aws_p5
  needs:
    # Builds targetted for EOS work on AWS as well as the build config is the same across both clusters.
    # TODO - Refactor build jobs to decouple EOS and AWS.
    - build-eos-aws-oci
  variables:
    AWS_HEAD_NODE: aws-pcluster-head
    AWS_HEAD_NODE_WORKDIR: /shared/gitlab-runner/nccl-ci/${CI_COMMIT_SHORT_SHA}
  script:
    - rsync -I -c -a --exclude ./.git ./ $AWS_HEAD_NODE:$AWS_HEAD_NODE_WORKDIR/

health-P100:
  stage: health
  rules:
    - when: always
  needs: []
  tags:
    - p100
  script:
    - srun --exclusive -t 00:02:00 -n 1 -c 8 -pP100 ./test/scripts/gitlab-runner-health-check.sh

health-P40:
  stage: health
  rules:
    - when: always
  needs: []
  tags:
    - p40
  script:
    - srun --exclusive -t 00:02:00 -n 1 -c 8 -pP40 ./test/scripts/gitlab-runner-health-check.sh

health-GP100:
  stage: health
  rules:
    - when: always
  needs: []
  tags:
    - gp100
  script:
    - srun --exclusive -t 00:02:00 -n 1 -c 8 -pGP100 ./test/scripts/gitlab-runner-health-check.sh

health-A40:
  stage: health
  rules:
    - when: always
  needs: []
  tags:
    - a40
  script:
    - srun --exclusive -t 00:02:00 -N 2 -c 2 -pA40 ./test/scripts/gitlab-runner-health-check.sh

health-A100:
  stage: health
  rules:
    - when: always
  needs: []
  tags:
    - a100pci
  script:
    - srun --exclusive -t 00:02:00 -n 1 -c 8 -pA100 ./test/scripts/gitlab-runner-health-check.sh

unit_tests-P100:
  stage: unit_tests
  rules:
    - when: always
  needs: ["build-classic","health-P100"]
  tags:
    - p100
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/gc-classic-config.sh"
    SLURM_TIME: 10
    SLURM_PARTITION: "P100"
    NNODES: 1
    NGPUS: 8
    NP: 1
    NCCL_HOME: build-gc
    RUN_MODE: "SALLOC_MPI"
  script:
    - ./test/scripts/ci/gitlab-runner-unit.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

unit_tests-P40:
  stage: unit_tests
  rules:
    - when: always
  needs: ["build-classic","health-P40"]
  tags:
    - p40
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/gc-classic-config.sh"
    SLURM_TIME: 10
    SLURM_PARTITION: "P40"
    NNODES: 1
    NGPUS: 8
    NP: 1
    NCCL_HOME: build-gc
    RUN_MODE: "SALLOC_MPI"
  script:
    - ./test/scripts/ci/gitlab-runner-unit.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

unit_tests-GP100:
  stage: unit_tests
  rules:
    - when: always
  needs: ["build-classic","health-GP100"]
  tags:
    - gp100
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/gc-classic-config.sh"
    SLURM_TIME: 10
    SLURM_PARTITION: "GP100"
    NNODES: 1
    NGPUS: 8
    NP: 1
    NCCL_HOME: build-gc
    RUN_MODE: "SALLOC_MPI"
  script:
    - ./test/scripts/ci/gitlab-runner-unit.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

unit_tests-A40-single:
  stage: unit_tests
  rules:
    - when: always
  needs: ["build-classic","health-A40"]
  tags:
    - a40
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/gc-classic-config.sh"
    SLURM_TIME: 10
    SLURM_PARTITION: "A40"
    NNODES: 1
    NGPUS: 1
    NP: 1
    NCCL_HOME: build-gc
    RUN_MODE: "SALLOC_MPI"
    DISABLE_MEMLEAK_DEFAULT: 1
    DISABLE_MEMLEAK_NETWORK: 1
  script:
    - ./test/scripts/ci/gitlab-runner-unit.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

unit_tests-A40-dual:
  stage: unit_tests
  rules:
    - when: always
  needs: ["build-classic"]
  tags:
    - a40
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/gc-classic-config.sh"
    SLURM_TIME: 10
    SLURM_PARTITION: "A40"
    NNODES: 1
    NGPUS: 2
    NP: 1
    NCCL_HOME: build-gc
    RUN_MODE: "SALLOC_MPI"
    DISABLE_MEMLEAK_NETWORK: 1
  script:
    - ./test/scripts/ci/gitlab-runner-unit.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

unit_tests-A100:
  stage: unit_tests
  rules:
    - when: always
  needs: ["build-classic","health-A100"]
  tags:
    - a100pci
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/gc-classic-config.sh"
    SLURM_TIME: 10
    SLURM_PARTITION: "A100"
    NNODES: 1
    NGPUS: 8
    NP: 1
    NCCL_HOME: build-gc
    RUN_MODE: "SALLOC_MPI"
  script:
    - ./test/scripts/ci/gitlab-runner-unit.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

unit_tests-eos:
  stage: unit_tests
  rules:
    - if: $RUN_ON_EOS == "1"
      when: always
    - when: never
  needs: ["build-eos-aws-oci"]
  tags:
    - nccl-eos
  variables:
    CI_BUILDS_DIR: "/lustre/fsw/coreai_libraries_nccl/$GITLAB_USER_LOGIN/gitlab-runner"
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/eos-config.sh"
    SLURM_TIME: 20
    NNODES: 1
    NGPUS: 8
    NP: 1
    NCCL_HOME: build-eos
    RUN_MODE: "MPI"
    SLURM_ACCOUNT: coreai_libraries_nccl
    DISABLE_MEMLEAK: "0" # Enable after addressing https://nvbugspro.nvidia.com/bug/4868411
    SRUN: "" # Needs to be empty for CI runner scripts performing cluster jobs
    PLANNED_RESERVED: "Planned"
    MPI_PARAMS: "--oversubscribe -n 2 -mca btl tcp,self"
  script:
    - export SALLOC="salloc -N ${NNODES} --ntasks-per-node ${NP} --exclusive --account=${SLURM_ACCOUNT} -J "${SLURM_ACCOUNT}-cicd::${GITLAB_USER_LOGIN}:unit::${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}" -t ${SLURM_TIME}"
    - $SALLOC ./test/scripts/ci/gitlab-runner-unit.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

unit_tests-AWS_H100_EFA:
  stage: unit_tests
  rules:
    - if: $RUN_ON_AWS == "1"
      when: always
    - when: never
  needs:
    - setup-AWS_H100_EFA
  tags:
    - aws_p5
  variables:
    GIT_STRATEGY: none
    AWS_HEAD_NODE: aws-pcluster-head
    AWS_HEAD_NODE_WORKDIR: /shared/gitlab-runner/nccl-ci/${CI_COMMIT_SHORT_SHA}
    RUN_SCRIPT: run_${CI_JOB_NAME}.sh
    TEST_CMD: ./test/scripts/ci/gitlab-runner-unit.sh
    JUNIT: junit_results_unit.xml
  before_script:
    - |
      cat > $RUN_SCRIPT << EOF
      export NCCL_DEBUG="WARN"
      export CLUSTER_CONFIG="docker/aws-config.sh"
      export SLURM_TIME=15
      export SLURM_PARTITION=compute
      export NNODES=1
      export NGPUS=8
      export NP=1
      export GRAPH=0
      export DISABLE_MEMLEAK_NETWORK=1
      export DISABLE_MEMLEAK=1
      export NCCL_HOME=build-eos
      export LD_LIBRARY_PATH=build-eos/lib:$LD_LIBRARY_PATH
      export RUN_MODE="SALLOC_MPI"
      export CI_PIPELINE_ID=${CI_PIPELINE_ID}
      export CI_JOB_NAME=${CI_JOB_NAME}
      export JUNIT=$JUNIT
      $TEST_CMD
      EOF
    - rsync -I -c $RUN_SCRIPT $AWS_HEAD_NODE:$AWS_HEAD_NODE_WORKDIR
  script:
    - ssh $AWS_HEAD_NODE "cd $AWS_HEAD_NODE_WORKDIR && bash -l $RUN_SCRIPT"
  after_script:
    - ssh $AWS_HEAD_NODE "cd $AWS_HEAD_NODE_WORKDIR && JUNIT=junit_results_unit.xml bash -l ./test/scripts/ci/finalize-junit.sh"
    - ssh $AWS_HEAD_NODE "test -d $AWS_HEAD_NODE_WORKDIR/failed && echo 'Failed dir exists' " && scp -r $AWS_HEAD_NODE:$AWS_HEAD_NODE_WORKDIR/failed .
    - scp $AWS_HEAD_NODE:$AWS_HEAD_NODE_WORKDIR/$JUNIT .
    - ls && ls failed && ls $JUNIT
  artifacts:
    when: always
    paths:
      - $JUNIT
      - $RUN_SCRIPT
      - "failed/**"
    reports:
      junit: $JUNIT
    expire_in: 48 hrs

unit_tests-draco_oci:
  stage: unit_tests
  rules:
    - if: $RUN_ON_DRACO_OCI == "1" && $RUN_UNIT_API_TESTS_ON_DRACO_OCI == "1"
      when: always
    - when: never
  needs:
    - build-eos-aws-oci
  tags:
    - draco-oci-iad
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/eos-config.sh"
    SLURM_TIME: 10
    NNODES: 1
    NGPUS: 8
    NP: 1
    NCCL_HOME: build-eos
    RUN_MODE: "MPI"
    SLURM_ACCOUNT: coreai_libraries_nccl
  script:
    - export SALLOC="salloc -N ${NNODES} --ntasks-per-node ${NP} --gpus-per-node $NGPUS --exclusive --account=${SLURM_ACCOUNT} -J "${SLURM_ACCOUNT}-cicd::${GITLAB_USER_LOGIN}:unit::${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}" -t ${SLURM_TIME}"
    - $SALLOC ./test/scripts/ci/gitlab-runner-unit.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

unit_tests-pre-nyx:
  stage: unit_tests
  rules:
    - if: $RUN_ON_PRE_NYX == "1"
      when: always
    - when: never
  needs: ["build-pre-nyx"]
  tags:
    - prenyx
  variables:
    CI_BUILDS_DIR: "/lustre/fsw/coreai_libraries_nccl/$GITLAB_USER_LOGIN/gitlab-runner"
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/pre-nyx-config.sh"
    SLURM_TIME: 20
    SLURM_PARTITION: batch
    NNODES: 1
    NGPUS: 8
    NP: 1
    NCCL_HOME: build-pre-nyx
    RUN_MODE: "SRUN_MPI"
    SLURM_ACCOUNT: coreai_libraries_nccl
  script:
    - export SALLOC="salloc -N ${NNODES} --exclusive --account=${SLURM_ACCOUNT} -J "${SLURM_ACCOUNT}-cicd::${GITLAB_USER_LOGIN}:unit::${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}" -t ${SLURM_TIME} -p ${SLURM_PARTITION}"
    - $SALLOC ./test/scripts/ci/gitlab-runner-unit.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

unit_tests-pre-tyche:
  stage: unit_tests
  rules:
    - if: $RUN_ON_PRE_TYCHE == "1"
      when: always
    - when: never
  needs: ["build-pre-tyche"]
  tags:
    - ptyche
  variables:
    CI_BUILDS_DIR: "/lustre/fsw/coreai_libraries_nccl/$GITLAB_USER_LOGIN/gitlab-runner"
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/pre-tyche-config.sh"
    SLURM_TIME: 20
    SLURM_PARTITION: batch
    NNODES: 1
    NGPUS: 4
    NP: 1
    NCCL_HOME: build-pre-tyche
    RUN_MODE: "SRUN_MPI"
    SLURM_ACCOUNT: coreai_libraries_nccl
    # Remove this once https://nvbugspro.nvidia.com/bug/5129632 is fixed to enable the enqueue_test_fifo unit test
    DISABLE_ENQUEUE_TESTS_FIFO: 1
  script:
    - export SALLOC="salloc -N ${NNODES} --exclusive --account=${SLURM_ACCOUNT} -J "${SLURM_ACCOUNT}-cicd::${GITLAB_USER_LOGIN}:unit::${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}" -t ${SLURM_TIME} -p ${SLURM_PARTITION}"
    - $SALLOC ./test/scripts/ci/gitlab-runner-unit.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

apitest-P100:
  stage: api_tests
  rules:
    - when: always
  needs: ["build-classic"]
  tags:
    - a100pci
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/gc-classic-config.sh"
    SLURM_TIME: 10
    RUN_MODE: "SALLOC_MPI"
    SLURM_PARTITION: "P100"
    NNODES: 1
    NGPUS: 8
    NP:    1
    NCCL_HOME: build-gc
  script:
    - ./test/scripts/ci/gitlab-runner-api.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

apitest-P40:
  stage: api_tests
  rules:
    - when: always
  needs: ["build-classic"]
  tags:
    - p40
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/gc-classic-config.sh"
    SLURM_TIME: 10
    RUN_MODE: "SALLOC_MPI"
    SLURM_PARTITION: "P40"
    NNODES: 1
    NGPUS: 8
    NP:    1
    NCCL_HOME: build-gc
  script:
    - ./test/scripts/ci/gitlab-runner-api.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

apitest-GP100:
  stage: api_tests
  rules:
    - when: always
  needs: ["build-classic"]
  tags:
    - gp100
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/gc-classic-config.sh"
    SLURM_TIME: 10
    RUN_MODE: "SALLOC_MPI"
    SLURM_PARTITION: "GP100"
    NNODES: 1
    NGPUS: 8
    NP:    1
    NCCL_HOME: build-gc
    # The NIC direct is not symmetric for rank 0 and 7; graph registration for sendrecv on rank 0 would
    # succeed but would fail on rank 7, this can cause hang.
    NCCL_GRAPH_REGISTER: 0
  script:
    - ./test/scripts/ci/gitlab-runner-api.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

apitest-A40:
  stage: api_tests
  rules:
    - when: always
  needs: ["build-classic"]
  tags:
    - a40
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/gc-classic-config.sh"
    SLURM_TIME: 10
    RUN_MODE: "SALLOC_MPI"
    SLURM_PARTITION: "A40"
    NNODES: 1
    NGPUS: 2
    NP:    1
    NCCL_HOME: build-gc
  script:
    - ./test/scripts/ci/gitlab-runner-api.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

apitest-A100:
  stage: api_tests
  rules:
    - when: always
  needs: ["build-classic"]
  tags:
    - a100pci
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/gc-classic-config.sh"
    SLURM_TIME: 10
    RUN_MODE: "SALLOC_MPI"
    SLURM_PARTITION: "A100"
    NNODES: 1
    NGPUS: 8
    NP:    1
    NCCL_HOME: build-gc
  script:
    - ./test/scripts/ci/gitlab-runner-api.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

apitest-DGX-1V:
  stage: api_tests
  rules:
    - if: $RUN_ON_DRACO == "1"
      when: always
    - when: never
  needs: [build-eos-aws-oci]
  tags:
    - dgx-1v
  variables:
    CUDA_HOME: "/gpfs/fs1/projects/sw_gpucomms/users/svc_nvshmem_ci/cuda/cuda-${CUDA_VERSION}"
    PARTITION_LIST: "batch_short_dgx1_m2"
    SRUN: "" # Needs to be empty for CI runner scripts performing cluster jobs
    SRUN_PARAMS: "--exclusive -N 1 -n 1 -G 8 -c 8 --account=coreai_libraries_nccl --nv-meta ml-model.nccl -t 00:20:00"
  script:
    - mv build-eos build
    - srun $SRUN_PARAMS -p $PARTITION_LIST ./test/scripts/gitlab-runner-apitest.sh minimal
  artifacts:
    when: always
    paths:
      - "**/core.*.*"
    expire_in: 48 hrs

apitest-DGX-2:
  stage: api_tests
  rules:
    - if: $RUN_ON_DRACO == "1"
      when: always
    - when: never
  needs: [build-eos-aws-oci]
  tags:
    - dgx-2
  variables:
    CUDA_HOME: "/gpfs/fs1/projects/sw_gpucomms/users/svc_nvshmem_ci/cuda/cuda-${CUDA_VERSION}"
    PARTITION_LIST: "batch_short_dgx2h_m2"
    SRUN: "" # Needs to be empty for CI runner scripts performing cluster jobs
    SRUN_PARAMS: "--exclusive --mem=0 -N 1 -n 1 -G 16 -c 16 --account=coreai_libraries_nccl --nv-meta ml-model.nccl -t 00:20:00"
  script:
    - mv build-eos build
    - srun $SRUN_PARAMS -p $PARTITION_LIST ./test/scripts/gitlab-runner-apitest.sh minimal
  artifacts:
    when: always
    paths:
      - "**/core.*.*"
    expire_in: 48 hrs

apitest-DGX-A100:
  stage: api_tests
  rules:
    - if: $RUN_ON_SELENE == "1" && $CUDA_VERSION != "10.2"
      when: always
    - when: never
  needs: [build-eos-aws-oci]
  tags:
    - dgx-a100
  variables:
    CUDA_HOME: "/project/nccl/toolkits/cuda-${CUDA_VERSION}/"
    NCCL_SOCKET_IFNAME: "ibp12s0"
    NCCL_CUMEM_ENABLE: "1"
    SRUN: "" # Needs to be empty for CI runner scripts performing cluster jobs
  script:
    - srun -n 1 --account=coreai_libraries_nccl -J "coreai_libraries_nccl-cicd::$GITLAB_USER_LOGIN:apitest::$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA" -pluna -t 00:30:00 ./test/scripts/gitlab-runner-apitest.sh
  artifacts:
    when: always
    paths:
      - "**/core.*.*"
    expire_in: 48 hrs

apitest-eos:
  stage: api_tests
  rules:
    - if: $RUN_ON_EOS == "1"
      when: always
    - when: never
  needs: ["build-eos-aws-oci"]
  tags:
    - nccl-eos
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/eos-config.sh"
    SLURM_TIME: 30
    RUN_MODE: "MPI"
    NNODES: 1
    NGPUS: 8
    NP: 1
    NCCL_HOME: build-eos
    SLURM_ACCOUNT: coreai_libraries_nccl
    CI_BUILDS_DIR: "/lustre/fsw/coreai_libraries_nccl/$GITLAB_USER_LOGIN/gitlab-runner"
    SRUN: "" # Needs to be empty for CI runner scripts performing cluster jobs
    PLANNED_RESERVED: "Planned"
  script:
    - export SALLOC="salloc -N ${NNODES} --ntasks-per-node ${NP} --exclusive --account=${SLURM_ACCOUNT} -J "${SLURM_ACCOUNT}-cicd::${GITLAB_USER_LOGIN}:apitest::${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}" -t ${SLURM_TIME}"
    - $SALLOC ./test/scripts/ci/gitlab-runner-api.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

apitest-AWS_H100_EFA:
  stage: api_tests
  rules:
    - if: $RUN_ON_AWS == "1"
      when: always
    - when: never
  needs:
    - [setup-AWS_H100_EFA,unit_tests-AWS_H100_EFA]
  tags:
    - aws_p5
  variables:
    GIT_STRATEGY: none
    AWS_HEAD_NODE: aws-pcluster-head
    AWS_HEAD_NODE_WORKDIR: /shared/gitlab-runner/nccl-ci/${CI_COMMIT_SHORT_SHA}
    RUN_SCRIPT: run_${CI_JOB_NAME}.sh
    TEST_CMD: ./test/scripts/ci/gitlab-runner-api.sh
    JUNIT: junit_results_apitest.xml
  before_script:
    - |
      cat > $RUN_SCRIPT << EOF
      export NCCL_DEBUG="WARN"
      export CLUSTER_CONFIG="docker/aws-config.sh"
      export SLURM_TIME=20
      export SLURM_PARTITION=compute
      export NNODES=1
      export NGPUS=8
      export SKIP_API_NO_P2P=1 # NvBug 5210770
      export NP=1
      export NCCL_HOME=build-eos
      export LD_LIBRARY_PATH=build-eos/lib:$LD_LIBRARY_PATH
      export RUN_MODE="SALLOC_MPI"
      export CI_PIPELINE_ID=${CI_PIPELINE_ID}
      export CI_JOB_NAME=${CI_JOB_NAME}
      export JUNIT=$JUNIT
      $TEST_CMD
      EOF
    - rsync -I -c $RUN_SCRIPT $AWS_HEAD_NODE:$AWS_HEAD_NODE_WORKDIR
  script:
    - ssh $AWS_HEAD_NODE "cd $AWS_HEAD_NODE_WORKDIR && bash -l $RUN_SCRIPT"
  after_script:
    - ssh $AWS_HEAD_NODE "cd $AWS_HEAD_NODE_WORKDIR && JUNIT=junit_results_apitest.xml bash -l ./test/scripts/ci/finalize-junit.sh"
    - ssh $AWS_HEAD_NODE "test -d $AWS_HEAD_NODE_WORKDIR/failed && echo 'Failed dir exists' " && scp -r $AWS_HEAD_NODE:$AWS_HEAD_NODE_WORKDIR/failed .
    - scp $AWS_HEAD_NODE:$AWS_HEAD_NODE_WORKDIR/$JUNIT .
    - ls && ls failed && ls $JUNIT
  artifacts:
    when: always
    paths:
      - $JUNIT
      - $RUN_SCRIPT
      - "failed/**"
    reports:
      junit: $JUNIT
    expire_in: 48 hrs

apitest-draco_oci:
  stage: api_tests
  rules:
    - if: $RUN_ON_DRACO_OCI == "1" && $RUN_UNIT_API_TESTS_ON_DRACO_OCI == "1"
      when: always
    - when: never
  needs:
    - build-eos-aws-oci
    - unit_tests-draco_oci
  tags:
    - draco-oci-iad
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/draco-oci-config.sh"
    SLURM_TIME: 20
    RUN_MODE: "MPI"
    NNODES: 1
    NGPUS: 8
    NP: 1
    NCCL_HOME: build-eos
    SLURM_ACCOUNT: coreai_libraries_nccl
  script:
    - export SALLOC="salloc -N ${NNODES} --ntasks-per-node ${NP} --gpus-per-node $NGPUS --exclusive --account=${SLURM_ACCOUNT} -J "${SLURM_ACCOUNT}-cicd::${GITLAB_USER_LOGIN}:apitest::${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}" -t ${SLURM_TIME}"
    - $SALLOC ./test/scripts/ci/gitlab-runner-api.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

apitest-pre-nyx:
  stage: api_tests
  rules:
    - if: $RUN_ON_PRE_NYX == "1"
      when: always
    - when: never
  needs: ["build-pre-nyx"]
  tags:
    - prenyx
  variables:
    CI_BUILDS_DIR: "/lustre/fsw/coreai_libraries_nccl/$GITLAB_USER_LOGIN/gitlab-runner"
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/pre-nyx-config.sh"
    SLURM_TIME: 30
    SLURM_PARTITION: batch
    RUN_MODE: "SRUN_MPI"
    NNODES: 1
    NGPUS: 8
    NP: 1
    NCCL_HOME: build-pre-nyx
    SLURM_ACCOUNT: coreai_libraries_nccl
  script:
    - export SALLOC="salloc -N ${NNODES} --exclusive --account=${SLURM_ACCOUNT} -J "${SLURM_ACCOUNT}-cicd::${GITLAB_USER_LOGIN}:apitest::${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}" -t ${SLURM_TIME} -p ${SLURM_PARTITION}"
    - $SALLOC ./test/scripts/ci/gitlab-runner-api.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

apitest-pre-tyche:
  stage: api_tests
  rules:
    - if: $RUN_ON_PRE_TYCHE == "1"
      when: always
    - when: never
  needs: ["build-pre-tyche"]
  tags:
    - ptyche
  variables:
    CI_BUILDS_DIR: "/lustre/fsw/coreai_libraries_nccl/$GITLAB_USER_LOGIN/gitlab-runner"
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/pre-tyche-config.sh"
    SLURM_TIME: 30
    SLURM_PARTITION: batch
    RUN_MODE: "SRUN_MPI"
    NNODES: 1
    NGPUS: 4
    NP: 1
    NCCL_HOME: build-pre-tyche
    SLURM_ACCOUNT: coreai_libraries_nccl
  script:
    - export SALLOC="salloc -N ${NNODES} --exclusive --account=${SLURM_ACCOUNT} -J "${SLURM_ACCOUNT}-cicd::${GITLAB_USER_LOGIN}:apitest::${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}" -t ${SLURM_TIME} -p ${SLURM_PARTITION}"
    - $SALLOC ./test/scripts/ci/gitlab-runner-api.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

perftest-P100:
  stage: perf_tests_single
  rules:
    - when: always
  needs: ["build-classic"]
  tags:
    - p100
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/gc-classic-config.sh"
    SLURM_TIME: 10
    RUN_MODE: "MPI"
    SLURM_PARTITION: "P100"
    MAX: "1G"
    NNODES: 1
    ENABLE_NVLS: 0
    GRAPH: 0
    NGPUS: 8
    NCCL_HOME: build-gc
    SALLOC: "salloc --exclusive -t 00:30:00 -N ${NNODES} -n ${NGPUS} -p ${SLURM_PARTITION}"
  script:
    - $SALLOC ./test/scripts/ci/gitlab-runner-perf.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

perftest-P40:
  stage: perf_tests_single
  rules:
    - when: always
  needs: ["build-classic"]
  tags:
    - p100
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/gc-classic-config.sh"
    SLURM_TIME: 10
    RUN_MODE: "SALLOC_MPI"
    SLURM_PARTITION: "P40"
    MAX: "1G"
    NNODES: 1
    ENABLE_NVLS: 0
    GRAPH: 0
    NGPUS: 8
    NP: 8
    NCCL_HOME: build-gc
  script:
    - ./test/scripts/ci/gitlab-runner-perf.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

perftest-GP100:
  stage: perf_tests_single
  rules:
    - when: always
  needs: ["build-classic"]
  tags:
    - gp100
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/gc-classic-config.sh"
    SLURM_TIME: 10
    RUN_MODE: "SALLOC_MPI"
    SLURM_PARTITION: "GP100"
    MAX: "1G"
    NNODES: 1
    ENABLE_NVLS: 0
    GRAPH: 0
    NGPUS: 8
    NP: 8
    NCCL_HOME: build-gc
  script:
    - ./test/scripts/ci/gitlab-runner-perf.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

nic-fusion-A40:
  stage: perf_tests_single
  rules:
    - when: always
  needs: [build-classic, apitest-A40]
  tags:
    - a40
  variables:
    NCCL_DEBUG: "WARN"
    MPI_HOME: "/opt/mpi/openmpi-1.10.7"
    CUDA_HOME: "/usr/local/cuda-${CUDA_VERSION}"
    NNODES: 1
    NGPUS: 2
    SALLOC: "salloc --exclusive -t 00:10:00 -N ${NNODES} -x gc12 -pA40"
  script:
    - pushd ext-net/mock
    - make
    - popd
    - ./test/scripts/gitlab-runner-mock-nic-fusion.sh test/nic-fusion/mock-a40-mixed-graph.xml test/nic-fusion/mock-a40-mixed-graph-1rpn.xml
  artifacts:
    when: always
    paths:
      - "**/core.*.*"
    expire_in: 48 hrs

perftest-A40:
  stage: perf_tests_single
  rules:
    - when: always
  needs: ["build-classic"]
  tags:
    - a40
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/gc-classic-config.sh"
    SLURM_TIME: 10
    RUN_MODE: "SALLOC_MPI"
    SLURM_PARTITION: "A40"
    MAX: "1G"
    NNODES: 1
    ENABLE_NVLS: 0
    GRAPH: 0
    NGPUS: 2
    NP: 2
    NCCL_HOME: build-gc
  script:
    - ./test/scripts/ci/gitlab-runner-perf.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

multi-perftest-A40:
  stage: perf_tests_multi
  rules:
    - when: always
  needs: ["build-classic"]
  tags:
    - a40
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/gc-classic-config.sh"
    SLURM_TIME: 10
    RUN_MODE: "SALLOC_MPI"
    SLURM_PARTITION: "A40"
    MAX: "1G"
    NNODES: 2
    ENABLE_NVLS: 0
    GRAPH: 0
    NGPUS: 2
    NP: 2
    NCCL_HOME: build-gc
  script:
    - ./test/scripts/ci/gitlab-runner-perf.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

perftest-A100:
  stage: perf_tests_single
  rules:
    - when: always
  needs: ["build-classic"]
  tags:
    - a100pci
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/gc-classic-config.sh"
    SLURM_TIME: 10
    RUN_MODE: "SALLOC_MPI"
    SLURM_PARTITION: "A100"
    MAX: "256M"
    NNODES: 1
    ENABLE_NVLS: 0
    GRAPH: 0
    NGPUS: 8
    NP: 8
    NCCL_HOME: build-gc
  script:
    - ./test/scripts/ci/gitlab-runner-perf.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

perftest-DGX-1V:
  stage: perf_tests_single
  rules:
    - if: $RUN_ON_DRACO == "1"
      when: always
    - when: never
  needs: [build-eos-aws-oci]
  tags:
    - dgx-1v
  variables:
    NCCL_DEBUG: "WARN"
    MPI_HOME: "/home/svc_nvshmem_ci/mpi/openmpi-1.10.7"
    CUDA_HOME: "/gpfs/fs1/projects/sw_gpucomms/users/svc_nvshmem_ci/cuda/cuda-${CUDA_VERSION}"
    PARTITION_LIST: "batch_short_dgx1_m2"
    NNODES: 1
    NGPUS: 8
    SALLOC: "" # Needs to be empty for CI runner scripts performing cluster jobs
  script:
    - mv build-eos build
    - salloc --gpus-per-node=${NGPUS} --ntasks-per-node=${NGPUS} -N ${NNODES} --account=coreai_libraries_nccl --nv-meta ml-model.nccl -p $PARTITION_LIST -t 00:25:00 ./test/scripts/gitlab-runner-perftest.sh 2G
  artifacts:
    when: always
    paths:
      - "**/core.*.*"
    expire_in: 48 hrs

perftest-DGX-2:
  stage: perf_tests_single
  rules:
    - if: $RUN_ON_DRACO == "1"
      when: always
    - when: never
  needs: [build-eos-aws-oci]
  tags:
    - dgx-2
  variables:
    NCCL_DEBUG: "WARN"
    MPI_HOME: "/home/svc_nvshmem_ci/mpi/openmpi-1.10.7"
    CUDA_HOME: "/gpfs/fs1/projects/sw_gpucomms/users/svc_nvshmem_ci/cuda/cuda-${CUDA_VERSION}"
    PARTITION_LIST: "batch_short_dgx2h_m2"
    NNODES: 1
    NGPUS: 16
    SALLOC: "" # Needs to be empty for CI runner scripts performing cluster jobs
  script:
    - mv build-eos build
    - salloc -N 1 --gpus-per-node=${NGPUS} --ntasks-per-node=${NGPUS} --account=coreai_libraries_nccl --nv-meta ml-model.nccl -p $PARTITION_LIST -t 00:35:00 ./test/scripts/gitlab-runner-perftest.sh 1G
  artifacts:
    when: always
    paths:
      - "**/core.*.*"
    expire_in: 48 hrs

perftest-DGX-A100:
  stage: perf_tests_single
  rules:
    - if: $RUN_ON_SELENE == "1" && $CUDA_VERSION != "10.2"
      when: always
    - when: never
  needs: [build-eos-aws-oci]
  tags:
    - dgx-a100
  variables:
    NCCL_DEBUG: "WARN"
    MPI_HOME: "/home/svcnccl/install/openmpi-1.10.7"
    CUDA_HOME: "/project/nccl/toolkits/cuda-${CUDA_VERSION}/"
    NCCL_CUMEM_ENABLE: "1"
    NNODES: 1
    NGPUS: 8
    SALLOC: "" # Needs to be empty for CI runner scripts performing cluster jobs
  script:
    - salloc -N ${NNODES} -n ${NGPUS} --account=coreai_libraries_nccl -pluna -J "coreai_libraries_nccl-cicd::$GITLAB_USER_LOGIN:perftest-single::$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA" -t 00:30:00 ./test/scripts/gitlab-runner-perftest.sh 16G
  artifacts:
    when: always
    paths:
      - "**/core.*.*"
    expire_in: 48 hrs

perftest-single-eos:
  stage: perf_tests_single
  rules:
    - if: $RUN_ON_EOS == "1"
      when: always
    - when: never
  needs: ["build-eos-aws-oci"]
  tags:
    - nccl-eos
  variables:
    CI_BUILDS_DIR: "/lustre/fsw/coreai_libraries_nccl/$GITLAB_USER_LOGIN/gitlab-runner"
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/eos-config.sh"
    SLURM_TIME: 20
    RUN_MODE: "MPI"
    NNODES: 1
    NGPUS: 8
    MAX: "1G"
    NP: 8
    SKIP_FT_INIT: 1
    NCCL_HOME: build-eos
    SLURM_ACCOUNT: coreai_libraries_nccl
  script:
    - export SALLOC="salloc -N ${NNODES} --ntasks-per-node ${NP} --exclusive --account=${SLURM_ACCOUNT} -J "${SLURM_ACCOUNT}-cicd::${GITLAB_USER_LOGIN}:perftest-single::${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}" -t ${SLURM_TIME}"
    - $SALLOC ./test/scripts/ci/gitlab-runner-perf.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

perftest_single-AWS_H100_EFA:
  stage: perf_tests_single
  rules:
    - if: $RUN_ON_AWS == "1"
      when: always
    - when: never
  needs:
    - [setup-AWS_H100_EFA,apitest-AWS_H100_EFA]
  tags:
    - aws_p5
  variables:
    GIT_STRATEGY: none
    AWS_HEAD_NODE: aws-pcluster-head
    AWS_HEAD_NODE_WORKDIR: /shared/gitlab-runner/nccl-ci/${CI_COMMIT_SHORT_SHA}/
    RUN_SCRIPT: run_${CI_JOB_NAME}.sh
    TEST_CMD: ./test/scripts/ci/gitlab-runner-perf.sh
    JUNIT: junit_results_perf_single.xml
  before_script:
    - |
      cat > $RUN_SCRIPT << EOF
      export NCCL_DEBUG="WARN"
      export CLUSTER_CONFIG="docker/aws-config.sh"
      export SLURM_TIME=10
      export SLURM_PARTITION=compute
      export NNODES=1
      export NGPUS=8
      export NP=8
      export GRAPH=0
      export MAX=1G
      export NCCL_HOME=build-eos
      export RUN_MODE="SALLOC_MPI"
      export CI_PIPELINE_ID=${CI_PIPELINE_ID}
      export CI_JOB_NAME=${CI_JOB_NAME}
      export LD_LIBRARY_PATH=build-eos/lib:$LD_LIBRARY_PATH
      export JUNIT=$JUNIT
      $TEST_CMD
      EOF
    - rsync -I -c $RUN_SCRIPT $AWS_HEAD_NODE:$AWS_HEAD_NODE_WORKDIR
  script:
    - ssh $AWS_HEAD_NODE "cd $AWS_HEAD_NODE_WORKDIR && bash -l $RUN_SCRIPT"
  after_script:
    - ssh $AWS_HEAD_NODE "cd $AWS_HEAD_NODE_WORKDIR && JUNIT=junit_results_perf_single.xml bash -l ./test/scripts/ci/finalize-junit.sh"
    - ssh $AWS_HEAD_NODE "test -d $AWS_HEAD_NODE_WORKDIR/failed && echo 'Failed dir exists' " && scp -r $AWS_HEAD_NODE:$AWS_HEAD_NODE_WORKDIR/failed .
    - scp $AWS_HEAD_NODE:$AWS_HEAD_NODE_WORKDIR/$JUNIT .
  artifacts:
    when: always
    paths:
      - $JUNIT
      - $RUN_SCRIPT
      - "failed/**"
    reports:
      junit: $JUNIT
    expire_in: 48 hrs

perftest_single-draco_oci:
  stage: perf_tests_single
  rules:
    - if: $RUN_ON_DRACO_OCI == "1"
      when: always
    - when: never
  needs:
    - build-eos-aws-oci
  tags:
    - draco-oci-iad
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/draco-oci-config.sh"
    SLURM_TIME: 20
    RUN_MODE: "MPI"
    NNODES: 1
    NGPUS: 8
    GRAPH: 0
    MAX: "1G"
    NP: 8
    SKIP_FT_INIT: 1
    NCCL_HOME: build-eos
    SLURM_ACCOUNT: coreai_libraries_nccl
    NO_LOOPBACK_NETWORKING: 1
  script:
    - export SALLOC="salloc -N ${NNODES} --gpus-per-node ${NGPUS} -n ${NP} --exclusive --account=${SLURM_ACCOUNT} -J "${SLURM_ACCOUNT}-cicd::${GITLAB_USER_LOGIN}:perftest-single::${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}" -t ${SLURM_TIME}"
    - $SALLOC ./test/scripts/ci/gitlab-runner-perf.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

perftest-single-pre-nyx:
  stage: perf_tests_single
  rules:
    - if: $RUN_ON_PRE_NYX == "1"
      when: always
    - when: never
  needs: ["build-pre-nyx"]
  tags:
    - prenyx
  variables:
    CI_BUILDS_DIR: "/lustre/fsw/coreai_libraries_nccl/$GITLAB_USER_LOGIN/gitlab-runner"
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/pre-nyx-config.sh"
    SLURM_TIME: 45
    SLURM_PARTITION: batch
    RUN_MODE: "SRUN_MPI"
    NNODES: 1
    NGPUS: 8
    MAX: "1G"
    NP: 8
    GRAPH: 0
    NCCL_HOME: build-pre-nyx
    SLURM_ACCOUNT: coreai_libraries_nccl
  script:
    - export SALLOC="salloc -N ${NNODES} --exclusive --account=${SLURM_ACCOUNT} -J "${SLURM_ACCOUNT}-cicd::${GITLAB_USER_LOGIN}:perftest-single::${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}" -t ${SLURM_TIME} -p ${SLURM_PARTITION}"
    - $SALLOC ./test/scripts/ci/gitlab-runner-perf.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

perftest-single-pre-tyche:
  stage: perf_tests_single
  rules:
    - if: $RUN_ON_PRE_TYCHE == "1"
      when: always
    - when: never
  needs: ["build-pre-tyche"]
  tags:
    - ptyche
  variables:
    CI_BUILDS_DIR: "/lustre/fsw/coreai_libraries_nccl/$GITLAB_USER_LOGIN/gitlab-runner"
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/pre-tyche-config.sh"
    SLURM_TIME: 45
    SLURM_PARTITION: batch
    RUN_MODE: "SRUN_MPI"
    NNODES: 1
    NGPUS: 4
    MAX: "1G"
    NP: 4
    GRAPH: 0
    NCCL_HOME: build-pre-tyche
    SLURM_ACCOUNT: coreai_libraries_nccl
  script:
    - export SALLOC="salloc -N ${NNODES} --exclusive --account=${SLURM_ACCOUNT} -J "${SLURM_ACCOUNT}-cicd::${GITLAB_USER_LOGIN}:perftest-single::${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}" -t ${SLURM_TIME} -p ${SLURM_PARTITION}"
    - $SALLOC ./test/scripts/ci/gitlab-runner-perf.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

perftest-multi-gc:
  stage: perf_tests_multi
  rules:
    - when: always
  needs: [build-classic]
  tags:
    - p100
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/gc-classic-config.sh"
    SLURM_TIME: 10
    RUN_MODE: "SALLOC_MPI"
    SLURM_HOSTS: "gc01,gc02"
    MAX: "1G"
    NNODES: 2
    ENABLE_NVLS: 0
    GRAPH: 0
    NGPUS: 8
    NP: 8
    NCCL_HOME: build-gc
  script:
    - ./test/scripts/ci/gitlab-runner-perf.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

perftest-sharp-gc:
  stage: perf_tests_multi
  rules:
    - when: always
  needs: [build-classic]
  tags:
    - p100
  variables:
    NCCL_IB_HCA: "mlx5_0"
    NCCL_DEBUG: "WARN"
    SHARP_HOME: "/opt/hpcx/v2.7/sharp"
    PLUGIN_PATH: "/opt/nccl-rdma-sharp-plugins/src/.libs"
    NNODES: 2
    NGPUS: 8
    NCCL_HOME: build-gc
    SALLOC: "salloc --exclusive -t 00:10:00 -N ${NNODES} --ntasks-per-node=${NGPUS} -w gc[01-02]"
  script:
    - source docker/gc-classic-config.sh && export CUDA_HOME=$(get_cuda_home) && export MPI_HOME=$(get_openmpi_home)
    - ./test/scripts/gitlab-runner-perftest-sharp.sh 128M 0
  artifacts:
    when: always
    paths:
      - "**/core.*.*"
    expire_in: 48 hrs

perftest-multi-DGX-1V:
  stage: perf_tests_multi
  rules:
    - when: always
  rules:
    - if: $RUN_ON_DRACO == "1"
      when: always
    - when: never
  needs: [build-eos-aws-oci]
  tags:
    - dgx-1v
  variables:
    MPI_HOME: "/home/svc_nvshmem_ci/mpi/openmpi-1.10.7"
    CUDA_HOME: "/gpfs/fs1/projects/sw_gpucomms/users/svc_nvshmem_ci/cuda/cuda-${CUDA_VERSION}"
    PARTITION_LIST: "batch_short_dgx1_m2"
    UCX_TLS: "tcp"
    NCCL_DEBUG_SUBSYS: "ENV"
    NCCL_IBEXT_DISABLE: "1"
    NNODES: $MULTI_PERFTEST_NODE_COUNT
    NGPUS: 8
    MPI_PARAMS: "-mca btl tcp,self -mca btl_tcp_if_include enp1s0f0"
    SALLOC: "" # Needs to be empty for CI runner scripts performing cluster jobs
    DRACO_SALLOC: "--exclusive --gpus-per-node=8 --ntasks-per-node=8 --account=coreai_libraries_nccl --nv-meta ml-model.nccl --exclusive -t 00:25:00"
  script:
    - mv build-eos build
    - let NUM_PROCESSES=$MULTI_PERFTEST_NODE_COUNT*8 && salloc $DRACO_SALLOC -N $MULTI_PERFTEST_NODE_COUNT -n $NUM_PROCESSES -G $NUM_PROCESSES -p $PARTITION_LIST ./test/scripts/gitlab-runner-perftest.sh 1G
  artifacts:
    when: always
    paths:
      - "**/core.*.*"
    expire_in: 48 hrs

# Disabled - Allocation timeouts cause too much noise
# perftest-multi-dgx-2:
#   stage: perf_tests_multi
#   rules:
#     - when: always
#   rules:
#     - if: $RUN_ON_DRACO == "1"
#       when: always
#     - when: never
#   needs: [build, unit_tests, perftest-DGX-2]
#   tags:
#     - dgx-2
#   variables:
#     MPI_HOME: "/home/svc_nvshmem_ci/mpi/openmpi-1.10.7"
#     CUDA_HOME: "/gpfs/fs1/projects/sw_gpucomms/users/svc_nvshmem_ci/cuda/cuda-${CUDA_VERSION}"
#     PARTITION_LIST: "batch_short_dgx2h_m2"
#     UCX_TLS: "tcp"
#     NCCL_DEBUG_SUBSYS: "ENV"
#     NCCL_DEBUG: "INFO"
#     NCCL_IBEXT_DISABLE: "1"
#     MPI_PARAMS: "-mca btl tcp,self -mca btl_tcp_if_include enp134s0f0np0"
#     SALLOC: "" # Needs to be empty for CI runner scripts performing cluster jobs
#     DRACO_SALLOC: "--exclusive --gpus-per-node=16 --ntasks-per-node=16 --account=coreai_libraries_nccl --nv-meta ml-model.nccl --exclusive -t 00:30:00"
#   script:
#     - let NUM_PROCESSES=$MULTI_PERFTEST_NODE_COUNT*16 && salloc $DRACO_SALLOC -N $MULTI_PERFTEST_NODE_COUNT -n $NUM_PROCESSES -G $NUM_PROCESSES -p $PARTITION_LIST ./test/scripts/gitlab-runner-perftest.sh 1G

perftest-multi-selene:
  stage: perf_tests_multi
  rules:
    - if: $RUN_ON_SELENE == "1" && $CUDA_VERSION != "10.2"
      when: always
    - when: never
  needs: [build-eos-aws-oci]
  tags:
    - dgx-a100
  variables:
    NCCL_DEBUG: "WARN"
    MPI_HOME: "/home/svcnccl/install/openmpi-1.10.7"
    CUDA_HOME: "/project/nccl/toolkits/cuda-${CUDA_VERSION}/"
    NCCL_IB_SL: "1"
    OMPI_MCA_btl: "^openib"
    NNODES: $MULTI_PERFTEST_NODE_COUNT
    NGPUS: 8
    OMPI_MCA_btl_tcp_if_include: "enp97s0f1"
    NCCL_CUMEM_ENABLE: "1"
    SALLOC: "" # Needs to be empty for CI runner scripts performing cluster jobs
  script:
    - let NUM_PROCESSES=$MULTI_PERFTEST_NODE_COUNT*8 && salloc -N $MULTI_PERFTEST_NODE_COUNT -n $NUM_PROCESSES --account=coreai_libraries_nccl -pluna -J "coreai_libraries_nccl-cicd::$GITLAB_USER_LOGIN:perftest-multi::$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA" -t 00:20:00 ./test/scripts/gitlab-runner-perftest.sh 16G 0

perftest-multi-eos:
  stage: perf_tests_multi
  rules:
    - if: $RUN_ON_EOS == "1"
      when: always
    - when: never
  needs: ["build-eos-aws-oci"]
  tags:
    - nccl-eos
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/eos-config.sh"
    SLURM_TIME: 30
    RUN_MODE: "MPI"
    CI_BUILDS_DIR: "/lustre/fsw/coreai_libraries_nccl/$GITLAB_USER_LOGIN/gitlab-runner"
    NCCL_IB_SL: "1"
    OMPI_MCA_btl: "^openib"
    MPI_PARAMS: "--oversubscribe --mca btl tcp,self --mca btl_tcp_if_include eth3"
    NNODES: $MULTI_PERFTEST_NODE_COUNT
    NGPUS: 8
    MAX: "1G"
    NP: 8
    SKIP_FT_INIT: 1
    NCCL_HOME: build-eos
    SLURM_ACCOUNT: coreai_libraries_nccl
    NNODES: $MULTI_PERFTEST_NODE_COUNT
  script:
    - export SALLOC="salloc -N ${NNODES} --ntasks-per-node ${NP} --exclusive --account=${SLURM_ACCOUNT} -J "${SLURM_ACCOUNT}-cicd::${GITLAB_USER_LOGIN}:perftest-multi::${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}" -t ${SLURM_TIME}"
    - $SALLOC ./test/scripts/ci/gitlab-runner-perf.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

perftest-sharp-selene:
  stage: perf_tests_multi
  rules:
    - if: $RUN_ON_SELENE_SHARP == "1" && $CUDA_VERSION != "10.2"
      when: always
    - when: never
  needs: [build-eos-aws-oci]
  tags:
    - dgx-a100
  variables:
    NCCL_DEBUG: "WARN"
    MPI_HOME: "/home/svcnccl/install/openmpi-1.10.7"
    CUDA_HOME: "/project/nccl/toolkits/cuda-${CUDA_VERSION}/"
    SHARP_HOME: "/lustre/fsw/nccl/hpcx/hpcx-v2.14-gcc-MLNX_OFED_LINUX-5-ubuntu20.04-cuda11-gdrcopy2-nccl2.16-x86_64/sharp"
    HPCX_UCX_LIB: "/lustre/fsw/nccl/hpcx/hpcx-v2.14-gcc-MLNX_OFED_LINUX-5-ubuntu20.04-cuda11-gdrcopy2-nccl2.16-x86_64/ucx/lib"
    PLUGIN_PATH: "/lustre/fsw/nccl/hpcx/hpcx-v2.14-gcc-MLNX_OFED_LINUX-5-ubuntu20.04-cuda11-gdrcopy2-nccl2.16-x86_64/nccl_rdma_sharp_plugin/lib"
    NCCL_IB_SL: "1"
    OMPI_MCA_btl: "^openib"
    NNODES: $MULTI_PERFTEST_NODE_COUNT
    NGPUS: 8
    OMPI_MCA_btl_tcp_if_include: "enp97s0f1"
    NCCL_CUMEM_ENABLE: "1"
    SALLOC: "" # Needs to be empty for CI runner scripts performing cluster jobs
  script:
    - let NUM_PROCESSES=$MULTI_PERFTEST_NODE_COUNT*8 && salloc -N $MULTI_PERFTEST_NODE_COUNT -n $NUM_PROCESSES --account=coreai_libraries_nccl -pluna --network=sharp -J "coreai_libraries_nccl-cicd::$GITLAB_USER_LOGIN:perftest-multi::$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA" -t $SHARP_MULTI_JOB_TIME ./test/scripts/gitlab-runner-perftest-sharp.sh 4G 0

perftest_multi-AWS_H100_EFA:
  stage: perf_tests_multi
  rules:
    - if: $RUN_ON_AWS == "1"
      when: always
    - when: never
  needs:
    - [setup-AWS_H100_EFA,perftest_single-AWS_H100_EFA]
  tags:
    - aws_p5
  variables:
    GIT_STRATEGY: none
    AWS_HEAD_NODE: aws-pcluster-head
    AWS_HEAD_NODE_WORKDIR: /shared/gitlab-runner/nccl-ci/${CI_COMMIT_SHORT_SHA}
    RUN_SCRIPT: run_${CI_JOB_NAME}.sh
    TEST_CMD: ./test/scripts/ci/gitlab-runner-perf.sh
    JUNIT: junit_results_perf_multi.xml
  before_script:
    - |
      cat > $RUN_SCRIPT << EOF
      export NCCL_DEBUG="WARN"
      export CLUSTER_CONFIG="docker/aws-config.sh"
      export SLURM_TIME=10
      export SLURM_PARTITION=compute
      export NGPUS=8
      export NNODES=4
      export MAX=1G
      export GRAPH=0
      export NP=8
      export NCCL_HOME=build-eos
      export LD_LIBRARY_PATH=build-eos/lib:$LD_LIBRARY_PATH
      export RUN_MODE="SALLOC_MPI"
      export CI_PIPELINE_ID=${CI_PIPELINE_ID}
      export CI_JOB_NAME=${CI_JOB_NAME}
      export JUNIT=$JUNIT
      export SKIP_FT_FINALIZE=1
      $TEST_CMD
      EOF
    - rsync -I -c $RUN_SCRIPT $AWS_HEAD_NODE:$AWS_HEAD_NODE_WORKDIR
  script:
    - ssh $AWS_HEAD_NODE "cd $AWS_HEAD_NODE_WORKDIR && bash -l $RUN_SCRIPT"
  after_script:
    - ssh $AWS_HEAD_NODE "cd $AWS_HEAD_NODE_WORKDIR && JUNIT=junit_results_perf_multi.xml bash -l ./test/scripts/ci/finalize-junit.sh"
    - ssh $AWS_HEAD_NODE "test -d $AWS_HEAD_NODE_WORKDIR/failed && echo 'Failed dir exists' " && scp -r $AWS_HEAD_NODE:$AWS_HEAD_NODE_WORKDIR/failed .
    - scp $AWS_HEAD_NODE:$AWS_HEAD_NODE_WORKDIR/$JUNIT .
  artifacts:
    when: always
    paths:
      - $JUNIT
      - $RUN_SCRIPT
      - "failed/**"
    reports:
      junit: $JUNIT
    expire_in: 48 hrs

perftest_multi-draco_oci:
  stage: perf_tests_multi
  rules:
    - if: $RUN_ON_DRACO_OCI == "1"
      when: always
    - when: never
  needs:
    - build-eos-aws-oci
  tags:
    - draco-oci-iad
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/draco-oci-config.sh"
    SLURM_TIME: 20
    RUN_MODE: "MPI"
    NNODES: $MULTI_PERFTEST_NODE_COUNT
    NGPUS: 8
    MAX: "1G"
    NP: 8
    GRAPH: 0
    SKIP_FT_INIT: 1
    NCCL_HOME: build-eos
    SLURM_ACCOUNT: coreai_libraries_nccl
    NO_LOOPBACK_NETWORKING: 1
  script:
    - export SALLOC="salloc -N ${NNODES} --gpus-per-node ${NGPUS} --ntasks-per-node ${NP} --exclusive --account=${SLURM_ACCOUNT} -J "${SLURM_ACCOUNT}-cicd::${GITLAB_USER_LOGIN}:perftest-multi::${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}" -t ${SLURM_TIME}"
    - $SALLOC ./test/scripts/ci/gitlab-runner-perf.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

perftest-multi-pre-nyx:
  stage: perf_tests_multi
  rules:
    - if: $RUN_ON_PRE_NYX == "1"
      when: always
    - when: never
  needs: ["build-pre-nyx"]
  tags:
    - prenyx
  variables:
    CI_BUILDS_DIR: "/lustre/fsw/coreai_libraries_nccl/$GITLAB_USER_LOGIN/gitlab-runner"
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/pre-nyx-config.sh"
    SLURM_TIME: 45
    SLURM_PARTITION: batch
    RUN_MODE: "SRUN_MPI"
    NGPUS: 8
    MAX: "1G"
    NP: 8
    GRAPH: 0
    NCCL_HOME: build-pre-nyx
    SLURM_ACCOUNT: coreai_libraries_nccl
    NNODES: $MULTI_PERFTEST_NODE_COUNT
  script:
    - export SALLOC="salloc -N ${NNODES} --exclusive --account=${SLURM_ACCOUNT} -J "${SLURM_ACCOUNT}-cicd::${GITLAB_USER_LOGIN}:perftest-multi::${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}" -t ${SLURM_TIME} -p ${SLURM_PARTITION}"
    - $SALLOC ./test/scripts/ci/gitlab-runner-perf.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

perftest-multi-pre-tyche:
  stage: perf_tests_multi
  rules:
    - if: $RUN_ON_PRE_TYCHE == "1"
      when: always
    - when: never
  needs: ["build-pre-tyche"]
  tags:
    - ptyche
  variables:
    CI_BUILDS_DIR: "/lustre/fsw/coreai_libraries_nccl/$GITLAB_USER_LOGIN/gitlab-runner"
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/pre-tyche-config.sh"
    SLURM_TIME: 45
    SLURM_PARTITION: batch
    RUN_MODE: "SRUN_MPI"
    NGPUS: 4
    MAX: "1G"
    NP: 4
    GRAPH: 0
    NCCL_HOME: build-pre-tyche
    SLURM_ACCOUNT: coreai_libraries_nccl
    NNODES: $MULTI_PERFTEST_NODE_COUNT
    # Remove this once https://nvbugspro.nvidia.com/bug/5129632 is fixed to enable ring 1rpn registration tests
    NO_LOOPBACK_NETWORKING: 1
  script:
    - export SALLOC="salloc -N ${NNODES} --exclusive --account=${SLURM_ACCOUNT} -J "${SLURM_ACCOUNT}-cicd::${GITLAB_USER_LOGIN}:perftest-multi::${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}" -t ${SLURM_TIME} -p ${SLURM_PARTITION}"
    - $SALLOC ./test/scripts/ci/gitlab-runner-perf.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs

perf-regression-single-DGX-A100:
  stage: perf_regression
  rules:
    - if: $RUN_ON_SELENE == "1" && $CUDA_VERSION != "10.2" && $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - when: never
  needs: [build-eos-aws-oci]
  tags:
    - dgx-a100
  variables:
    NCCL_DEBUG: "WARN"
    MPI_HOME: "/home/svcnccl/install/openmpi-1.10.7"
    CUDA_HOME: "/project/nccl/toolkits/cuda-${CUDA_VERSION}/"
    NVCC_GENCODE: " -gencode=arch=compute_80,code=sm_80"
    NCCL_CUMEM_ENABLE: "1"
    GPU_APPLICATION_CLOCK: 1410
  script:
    - ./test/scripts/gitlab-runner-build-baseline.sh $CI_MERGE_REQUEST_DIFF_BASE_SHA
    - salloc -N 1 -n 8 --account=coreai_libraries_nccl -pluna -J "coreai_libraries_nccl-cicd::$GITLAB_USER_LOGIN:perftest-single-regression::$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA" -t $SINGLE_REGRESSION_SALLOC_TIME ./test/scripts/gitlab-runner-compare-perf.sh $REGRESSION_THRESHOLD $REGRESSION_ITERATIONS $REGRESSION_CHECK_CPU_OVERHEAD $CI_MERGE_REQUEST_DIFF_BASE_SHA
  cache:
    key: "build-${REGRESSION_BASELINE}"
    paths:
      - "build-${REGRESSION_BASELINE}/lib"
      - "build-${REGRESSION_BASELINE}/test/perf"
    key: "build-${CI_MERGE_REQUEST_DIFF_BASE_SHA}"
    paths:
      - "build-${CI_MERGE_REQUEST_DIFF_BASE_SHA}/lib"
      - "build-${CI_MERGE_REQUEST_DIFF_BASE_SHA}/test/perf"

self-test-pytorch-container-eos:
  stage: perf_tests_single
  rules:
    - if: $RUN_ON_EOS == "1" && ( $RUN_DLFW_TESTS == "1" || $CI_PIPELINE_SOURCE == 'schedule' )
      when: always
    - when: never
  tags:
    - nccl-eos
  needs:
    - build-dlfw-pytorch-container
  parallel: 4
  variables:
    CONTAINER: gitlab-master.nvidia.com/dl/dgx/pytorch:main-py3-devel
    CI_BUILDS_DIR: "/lustre/fsw/coreai_libraries_nccl/$GITLAB_USER_LOGIN/gitlab-runner"
  script:
    - chmod +x test/scripts/dlfw/*.sh
    - srun -N1 --exclusive -t60 -A coreai_libraries_nccl -J coreai_libraries_nccl-bewilliams.test-cont --container-image="$CONTAINER" --container-mounts=$(pwd):/workspace/nccl /workspace/nccl/test/scripts/dlfw/run_dlfw_selftest.sh
  timeout: 48 hours

perf-regression-multi-DGX-A100:
  stage: perf_regression
  rules:
    - if: $RUN_ON_SELENE == "1" && $CUDA_VERSION != "10.2" && $CI_PIPELINE_SOURCE != "merge_request_event" && $RUN_MULTI_REGRESSION == "1"
      when: always
    - when: never
    - if: $REGRESSION_BASELINE == ""
      variables:
        REGRESSION_BASELINE: "${REGRESSION_BASELINE_TAG}"
  needs: [build-eos-aws-oci]
  tags:
    - dgx-a100
  variables:
    NCCL_DEBUG: "WARN"
    MPI_HOME: "/home/svcnccl/install/openmpi-1.10.7"
    CUDA_HOME: "/project/nccl/toolkits/cuda-${CUDA_VERSION}/"
    NVCC_GENCODE: " -gencode=arch=compute_80,code=sm_80"
    NCCL_IB_SL: "1"
    NCCL_CUMEM_ENABLE: "1"
    OMPI_MCA_btl: "^openib"
    OMPI_MCA_btl_tcp_if_include: "enp97s0f1"
    GPU_APPLICATION_CLOCK: 1410
  script:
    - ./test/scripts/gitlab-runner-build-baseline.sh $CI_MERGE_REQUEST_DIFF_BASE_SHA
    - let NUM_PROCESSES=$MULTI_PERFTEST_NODE_COUNT*8 && salloc -N $MULTI_PERFTEST_NODE_COUNT -n $NUM_PROCESSES --account=coreai_libraries_nccl -pluna -J "coreai_libraries_nccl-cicd::$GITLAB_USER_LOGIN:perftest-multi-regression::$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA" -t $MULTI_REGRESSION_SALLOC_TIME ./test/scripts/gitlab-runner-compare-perf.sh $REGRESSION_THRESHOLD $REGRESSION_ITERATIONS $REGRESSION_CHECK_CPU_OVERHEAD $CI_MERGE_REQUEST_DIFF_BASE_SHA
  cache:
    key: "build-${REGRESSION_BASELINE}"
    paths:
      - "build-${REGRESSION_BASELINE}/lib"
      - "build-${REGRESSION_BASELINE}/test/perf"
    key: "build-${CI_MERGE_REQUEST_DIFF_BASE_SHA}"
    paths:
      - "build-${CI_MERGE_REQUEST_DIFF_BASE_SHA}/lib"
      - "build-${CI_MERGE_REQUEST_DIFF_BASE_SHA}/test/perf"

QA-team-ci:
  stage: perf_regression
  rules:
    - when: always
  tags:
    - cqa_host_runner
  script:
    - mv build-gc build
    - bash $CI_BUILDS_DIR/CI/ci_perftest.sh

replay-multi-gc:
  stage: replay_tests
  rules:
    - when: always
  needs: [build-classic]
  tags:
    - p100
  variables:
    NCCL_IB_HCA: "mlx5_0"
    NCCL_HOME: build-gc
    NCCL_DEBUG: "WARN"
    SALLOC_RESNET: "salloc --exclusive -t 00:05:00 -N 2 -n 8 -w gc[01-02]"
    SALLOC_SELF_MULTI: "salloc --exclusive -t 00:05:00 -N 2 -n 16 -w gc[01-02]"
    SALLOC_SELF_SINGLE: "salloc --exclusive -t 00:05:00 -N 1 -n 8 -pP100"
  script:
    - source docker/gc-classic-config.sh && export CUDA_HOME=$(get_cuda_home) && export MPI_HOME=$(get_openmpi_home)
    - SALLOC=$SALLOC_RESNET ./test/scripts/gitlab-runner-replay-test.sh test/replay/traces/resnet_2x4_trace.txt
    - ./test/scripts/gitlab-runner-replay-self-test.sh
  artifacts:
    when: always
    paths:
      - "**/core.*.*"
    expire_in: 48 hrs

summarize-pipeline:
  stage: summary
  rules:
    - when: always
  tags:
    - build
  script:
    - ./test/scripts/gitlab-runner-summary.sh

profiler-tests-A100:
  stage: profiler_tests
  rules:
    - when: always
  needs: ["build-classic"]
  tags:
    - a100pci
  variables:
    NCCL_DEBUG: "WARN"
    CLUSTER_CONFIG: "docker/gc-classic-config.sh"
    SLURM_TIME: 10
    RUN_MODE: "SALLOC_MPI"
    SLURM_PARTITION: "A100"
    NNODES: 1
    ENABLE_NVLS: 0
    NGPUS: 4
    NP: 4
    NCCL_HOME: build-gc
  script:
    - ./test/scripts/ci/gitlab-runner-profiler.sh
  after_script:
    - ./test/scripts/ci/finalize-junit.sh
  artifacts:
    when: always
    paths:
      - "failed/**"
      - "junit_results.xml"
    reports:
      junit: junit_results.xml
    expire_in: 48 hrs
