stages:
  - build
  - unit_tests
  - api_tests
  - perf_tests_single
  - perf_tests_multi

build:
  stage: build
  tags:
    - build
  variables:
    MPI_HOME: "/opt/mpi/openmpi-1.10.7"
    CUDA_HOME: "/usr/local/cuda-11.0"
  script:
    - make -j test.build MPI=1 MPI_HOME=$MPI_HOME CUDA_HOME=$CUDA_HOME
  artifacts:
    paths:
      - build
    expire_in: 1 day
  interruptible: true

unit_tests:
  stage: unit_tests
  tags:
    - build
  variables:
    CUDA_HOME: "/usr/local/cuda-11.0"
  script:
    - (cd build/test/unit; LD_LIBRARY_PATH=$PWD/../../lib:$CUDA_HOME/lib64 ./graph_test)
  interruptible: true

apitest-P100:
  stage: api_tests
  tags:
    - p100
  variables:
    NCCL_IB_HCA: "mlx5_0"
    CUDA_HOME: "/usr/local/cuda-11.0"
    SRUN: "srun -t 00:05:00 -n 1 -c 8 -pP100"
  script:
    - ./test/scripts/gitlab-runner-apitest.sh
  interruptible: true

apitest-P40:
  stage: api_tests
  tags:
    - p40
  variables:
    NCCL_IB_HCA: "mlx5_0"
    CUDA_HOME: "/usr/local/cuda-11.0"
    SRUN: "srun -t 00:05:00 -n 1 -c 8 -pP40"
  script:
    - ./test/scripts/gitlab-runner-apitest.sh
  interruptible: true

apitest-GP100:
  stage: api_tests
  tags:
    - gp100
  variables:
    CUDA_HOME: "/usr/local/cuda-11.0"
    SRUN: "srun -t 00:05:00 -n 1 -c 2 -pGP100"
  script:
    - ./test/scripts/gitlab-runner-apitest.sh
  interruptible: true

apitest-M40:
  stage: api_tests
  tags:
    - m40
  variables:
    CUDA_HOME: "/usr/local/cuda-11.0"
    SRUN: "srun -t 00:05:00 -n 1 -c 8 -pM40"
  script:
    - ./test/scripts/gitlab-runner-apitest.sh
  interruptible: true

apitest-K40:
  stage: api_tests
  tags:
    - k40
  variables:
    CUDA_HOME: "/usr/local/cuda-11.0"
    SRUN: "srun -t 00:05:00 -n 1 -c 8 -pK40"
  script:
    - ./test/scripts/gitlab-runner-apitest.sh
  interruptible: true

apitest-K80:
  stage: api_tests
  tags:
    - k80
  variables:
    CUDA_HOME: "/usr/local/cuda-11.0"
    SRUN: "srun -t 00:05:00 -n 1 -c 16 -pK80"
  script:
    - ./test/scripts/gitlab-runner-apitest.sh minimal
  interruptible: true

apitest-A100:
  stage: api_tests
  tags:
    - a100pci
  variables:
    CUDA_HOME: "/usr/local/cuda-11.0"
    SRUN: "srun -t 00:05:00 -n 1 -c 8 -pA100"
  script:
    - ./test/scripts/gitlab-runner-apitest.sh
  interruptible: true

#apitest-DGX-1V:
#  stage: api_tests
#  tags:
#    - dgx-1v
#  variables:
#    CUDA_HOME: "/home/sjeaugey/prom-dev/cuda-11.0"
#    SRUN: ""
#  script:
#    - srun -n 1 --account=sw-gpu -pbatch -t 00:05:00 ./test/scripts/gitlab-runner-apitest.sh
#  interruptible: true

#apitest-DGX-A100:
#  stage: api_tests
#  tags:
#    - dgx-a100
#  variables:
#    CUDA_HOME: "/project/share/cuda/cuda-11.0.221/"
#    NCCL_SOCKET_IFNAME: "ibp12s0"
#    SRUN: ""
#  script:
#    - srun -n 1 --account=nccl -J "nccl-cicd::$GITLAB_USER_LOGIN:apitest::$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA" -pluna -t 00:05:00 ./test/scripts/gitlab-runner-apitest.sh
#  interruptible: true

perftest-P100:
  stage: perf_tests_single
  tags:
    - p100
  variables:
    NCCL_DEBUG: "WARN"
    MPI_HOME: "/opt/mpi/openmpi-1.10.7"
    CUDA_HOME: "/usr/local/cuda-11.0"
    SALLOC: "salloc -t 00:05:00 -n 8 -pP100"
  script:
    - ./test/scripts/gitlab-runner-perftest.sh
  interruptible: true

perftest-P40:
  stage: perf_tests_single
  tags:
    - p40
  variables:
    NCCL_DEBUG: "WARN"
    MPI_HOME: "/opt/mpi/openmpi-1.10.7"
    CUDA_HOME: "/usr/local/cuda-11.0"
    SALLOC: "salloc -t 00:05:00 -n 8 -pP40"
  script:
    - ./test/scripts/gitlab-runner-perftest.sh
  interruptible: true

perftest-GP100:
  stage: perf_tests_single
  tags:
    - gp100
  variables:
    NCCL_DEBUG: "WARN"
    MPI_HOME: "/opt/mpi/openmpi-1.10.7"
    CUDA_HOME: "/usr/local/cuda-11.0"
    SALLOC: "salloc -t 00:05:00 -n 2 -pGP100"
  script:
    - ./test/scripts/gitlab-runner-perftest.sh
  interruptible: true

perftest-M40:
  stage: perf_tests_single
  tags:
    - m40
  variables:
    NCCL_DEBUG: "WARN"
    MPI_HOME: "/opt/mpi/openmpi-1.10.7"
    CUDA_HOME: "/usr/local/cuda-11.0"
    SALLOC: "salloc -t 00:05:00 -n 8 -pM40"
  script:
    - ./test/scripts/gitlab-runner-perftest.sh
  interruptible: true

perftest-K80:
  stage: perf_tests_single
  tags:
    - k80
  variables:
    NCCL_DEBUG: "WARN"
    MPI_HOME: "/opt/mpi/openmpi-1.10.7"
    CUDA_HOME: "/usr/local/cuda-11.0"
    SALLOC: "salloc -t 00:05:00 -N 1 -n 16 -pK80"
  script:
    - ./test/scripts/gitlab-runner-perftest.sh 256M
  interruptible: true

perftest-K40:
  stage: perf_tests_single
  tags:
    - k40
  variables:
    NCCL_DEBUG: "WARN"
    MPI_HOME: "/opt/mpi/openmpi-1.10.7"
    CUDA_HOME: "/usr/local/cuda-11.0"
    SALLOC: "salloc -t 00:05:00 -n 8 -pK40"
  script:
    - ./test/scripts/gitlab-runner-perftest.sh
  interruptible: true

perftest-A100:
  stage: perf_tests_single
  tags:
    - a100pci
  variables:
    NCCL_DEBUG: "WARN"
    MPI_HOME: "/opt/mpi/openmpi-1.10.7"
    CUDA_HOME: "/usr/local/cuda-11.0"
    SALLOC: "salloc -t 00:05:00 -n 8 -pA100"
  script:
    - ./test/scripts/gitlab-runner-perftest.sh
  interruptible: true

#perftest-DGX-1V:
#  stage: perf_tests_single
#  tags:
#    - dgx-1v
#  variables:
#    NCCL_DEBUG: "WARN"
#    MPI_HOME: "/home/sjeaugey/prom-dev/mpi/openmpi-1.10.7"
#    CUDA_HOME: "/home/sjeaugey/prom-dev/cuda-11.0"
#    SALLOC: ""
#  script:
#    - salloc -N 1 -n 8 --account=sw-gpu -pbatch -t 00:05:00 ./test/scripts/gitlab-runner-perftest.sh 4G
#  interruptible: true

#perftest-DGX-A100:
#  stage: perf_tests_single
#  tags:
#    - dgx-a100
#  variables:
#    NCCL_DEBUG: "WARN"
#    MPI_HOME: "/home/svcnccl/install/openmpi-1.10.7"
#    CUDA_HOME: "/project/share/cuda/cuda-11.0.221/"
#    SALLOC: ""
#  script:
#    - salloc -N 1 -n 8 --account=nccl -pluna -J "nccl-cicd::$GITLAB_USER_LOGIN:perftest-single::$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA" -t 00:05:00 ./test/scripts/gitlab-runner-perftest.sh 16G
#  interruptible: true

perftest-multi-gc:
  stage: perf_tests_multi
  tags:
    - p100
  variables:
    NCCL_IB_HCA: "mlx5_0"
    NCCL_DEBUG: "WARN"
    MPI_HOME: "/opt/mpi/openmpi-1.10.7"
    CUDA_HOME: "/usr/local/cuda-11.0"
    SALLOC: "salloc -t 00:05:00 -N 4 -n 32 -w gc[01-03,05]"
  script:
    - ./test/scripts/gitlab-runner-perftest.sh 128M
  interruptible: true

#perftest-multi-prom:
#  stage: perf_tests_multi
#  tags:
#    - dgx-1v
#  variables:
#    NCCL_DEBUG: "WARN"
#    MPI_HOME: "/home/sjeaugey/prom-dev/mpi/openmpi-1.10.7"
#    CUDA_HOME: "/home/sjeaugey/prom-dev/cuda-11.0"
#    OMPI_MCA_oob_tcp_if_include: "10.33.12.0/24"
#    OMPI_MCA_btl: "tcp,self"
#    OMPI_MCA_btl_tcp_if_include: "10.33.12.0/24"
#    SALLOC: ""
#  script:
#    - salloc -N 4 -n 32 --account=sw-gpu -pbatch -t 00:05:00 ./test/scripts/gitlab-runner-perftest.sh 4G
#  interruptible: true

#perftest-multi-selene:
#  stage: perf_tests_multi
#  tags:
#    - dgx-a100
#  variables:
#    NCCL_DEBUG: "WARN"
#    MPI_HOME: "/home/svcnccl/install/openmpi-1.10.7"
#    CUDA_HOME: "/project/share/cuda/cuda-11.0.221/"
#    NCCL_IB_SL: "1"
#    OMPI_MCA_btl: "^openib"
#    OMPI_MCA_btl_tcp_if_include: "enp97s0f1"
#    SALLOC: ""
#  script:
#    - salloc -N 4 -n 32 --account=nccl -pluna -J "nccl-cicd::$GITLAB_USER_LOGIN:perftest-multi::$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA" -t 00:10:00 ./test/scripts/gitlab-runner-perftest.sh 16G
#  interruptible: true

