/*
 * Copyright 1993-2014 by NVIDIA Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to NVIDIA
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of NVIDIA Corporation is prohibited.
 */

#ifndef __cuda_etbl_tools_module_h__
#define __cuda_etbl_tools_module_h__

#include "cuda.h"

#include "cuda_uuid.h"
#include "cuda_packing.h"
#include "cuda_stdint.h"

#include "cuda_etbl/tools_common_types.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus


// Properties of a global-variable defined in a CUmodule.
typedef struct CUtoolsGlobalVariableProperties_st {
    uint32_t struct_size;
    uint32_t reserved0;

    const char* pName;
    void *devptr;
    size_t sizeInBytes;
    void *reserved1;

    uint32_t isUVMManaged;         // boolean, non zero means this is a UVM managed allocation
    uint32_t reserved2;
} CUtoolsGlobalVariableProperties;

// Types of CUfunctions
typedef enum CUtools_function_type_enum {
    CU_TOOLS_FUNCTION_TYPE_INVALID             = 0x0,
    CU_TOOLS_FUNCTION_TYPE_DEVICE              = 0x1,
    CU_TOOLS_FUNCTION_TYPE_GLOBAL              = 0x2,
    // --- always add new constants to the end here ---
    CU_TOOLS_FUNCTION_TYPE_SIZE,
    CU_TOOLS_FUNCTION_TYPE_INT                 = 0x7fffffff
} CUtools_function_type;

/// \brief Callback signature for ModuleEnumerateGlobalVariables()
typedef void (CUDAAPI *CUtoolsEnumerateGlobalVariablesCallback)(
    void* pUserData,
    CUtoolsGlobalVariableProperties* pGlobalVariableProperties);

/// \brief Callback signature for ModuleEnumerateGlobalFunctions()
typedef void (CUDAAPI *CUtoolsEnumerateGlobalFunctionsCallback)(
    void* pUserData,
    CUfunction func,
    const char* pName);

/// \brief Callback signature for ModuleEnumerateFunctions()
typedef void (CUDAAPI *CUtoolsEnumerateFunctionsCallback)(
    void* pUserData,
    CUfunction func);

//  Runtime configuration of a CUfunction.
typedef struct CUtoolsFunctionLaunchConfig_st {
    uint32_t struct_size;
    uint32_t reserved0;

    /// read/write field; takes effect on next launch
    uint32_t localRegistersPerThread;
    /// On Tesla, this is total LMem size per thread.
    /// On Fermi+, this is LMemLoSz (per thread)
    /// read/write field
    uint32_t lmemLoSize;

    /// read-only field
    uint32_t localMemTotal;

    uint32_t reserved1;

    /// threadEntryPointPc is where all CTAs begin executing.
    /// read-only field
    uint64_t threadEntryPointPc;
    /// the portion of shared-mem-per-block that was statically requested
    /// read-only field
    uint32_t staticSharedMemPerBlock;
    /// the portion of shared-mem-per-block that was dynamically requested
    /// Note that CNP (device-side) launches don't use this field
    /// read/write field
    uint32_t dynamicSharedMemPerBlock;
    /// total shared-mem-per-block.  Ignored by FunctionSetLaunchConfiguration.
    /// read-only field
    uint32_t totalSharedMemPerBlock;
    /// number of barriers required by each CTA
    /// read/write field
    uint32_t barrierCount;

    // NOTE: Call CalcLMemHiSize() or FunctionCalcLMemHiSize() to get lmemHiSize.

    /// On Tesla, always zero.
    /// On Fermi+, this is the amount of lmemHi space the function requires.
    /// Only applies to __global__ functions.  (it includes the worst-case
    /// call-stack that could occur in the __global__ function)
    /// read-only field
    uint32_t funcDataStackSize;

    /// On Tesla, always zero.
    /// On Fermi+, this is the function's stack-frame size.
    uint32_t funcStackFrameSize;

    /// Grid and block dimensions
    uint32_t blockDimX;
    uint32_t blockDimY;
    uint32_t blockDimZ;
    uint32_t gridDimX;
    uint32_t gridDimY;
    uint32_t gridDimZ;

    /// Sync stack size per warp
    /// size generated by the compiler, see CUfunc::syncStackSize.compiler
    /// read-only field
    uint32_t syncStackSizeCompiler;
    /// extra size required by the driver, see CUfunc::syncStackSize.driver
    /// read-only field
    uint32_t syncStackSizeDriver;
    /// should always be compiler + driver unless modified by tools, see CUfunc::syncStackSize.launch
    /// read/write field
    uint32_t syncStackSizeLaunch;

    uint32_t reserved2;
} CUtoolsFunctionLaunchConfig;

//  Mem-handles for function-related memories.
typedef struct CUtoolsFunctionMemObjHandles_st {
    uint32_t struct_size;
    uint32_t reserved0;

    /// hLMem should always be valid.
    CUtoolsMemObjHandle hMemObjLMem;
    /// hCrs should only be valid on Tesla.
    CUtoolsMemObjHandle hMemObjCrs;
    /// pMemObjInstructions's memblock can include many functions.
    /// CUtoolsFunctionLaunchConfig::threadEntryPointPC should
    ///     contain the offset of this memory-object within its memblock.
    CUtoolsMemObjHandle hMemObjInstructions;
    void *reserved1;
} CUtoolsFunctionMemObjHandles;

typedef enum CUtools_cache_config_enum {
    CU_TOOLS_CACHE_CONFIG_PREFER_NONE              = 0x00,
    CU_TOOLS_CACHE_CONFIG_PREFER_SHARED            = 0x01,
    CU_TOOLS_CACHE_CONFIG_PREFER_L1                = 0x02,
    CU_TOOLS_CACHE_CONFIG_PREFER_EQUAL             = 0x03,
    // --- always add new constants to the end here ---
    CU_TOOLS_CACHE_CONFIG_SIZE,
    CU_TOOLS_CACHE_CONFIG_FORCE_INT                = 0x7fffffff
} CUtools_cache_config;  

/// Properties of a kernel parameter.
typedef struct CUtoolsKernelParamInfo_st {
    /// For versioning.  You can add members to the end, but be sure to
    /// guarantee sizeof for this struct grows when you add members, so
    /// clients can correctly determine by the size whether a member is
    /// present by checking struct_size.
    uint32_t struct_size;
    uint32_t reserved0;

    /// Size in bytes of the kernel param.
    size_t size;
    /// Offset in bytes of the kernel param within binary blob of parameters.
    size_t offset;
    /// bool, nonzero for shared memory parameters.
    size_t isSmemParam;
    void *reserved1;
} CUtoolsKernelParamInfo;

/// Information about the CNP patch state/requirements for a function.
typedef struct CUtoolsFunctionCnpPatchInfo_st {
    /// For versioning.  You can add members to the end, but be sure to
    /// guarantee sizeof for this struct grows when you add members, so
    /// clients can correctly determine by the size whether a member is
    /// present by checking struct_size.
    uint32_t struct_size;

    /// Does this function need to be launched through the entry/exit function.
    /// This attribute is only ever set for launch able functions, i.e.
    /// __global__ functions and not __device__ functions. A device function
    /// with this attribute not set can be reached through a global function
    /// with this attribute set.
    uint32_t useEntryExitWrapper;
    /// Are blockidx s2r instructions patched in this function.
    uint32_t patchBlockIdx;
    /// Are exit instructions patched in this function.
    /// On Maxwell we never patch exit instructions as we've added functionality
    /// into the hardware with the PEXIT/EXIT instruction pair that removes the
    /// need for us to patch all exit points. 
    uint32_t patchExit;
} CUtoolsFunctionCnpPatchInfo;

/// \brief ApiModule provides functions to retrieve state from CUmodule, CUfunction
CU_DEFINE_UUID(CU_ETID_ToolsModule,
    0xbe3f166e, 0x58b9, 0x4d44, 0x83, 0x5c, 0xe1, 0x82, 0xaf, 0xf1, 0x99, 0x1e);

typedef struct CUetblToolsModule_st {
    // This export table supports versioning by adding to the end without changing
    // the ETID.  The struct_size field will always be set to the size in bytes of
    // the entire export table structure.
    size_t struct_size;

    /// \brief Get launch-parameters for the function, such as local-mem size per thread.
    /// TODO: This assumes that ucode exists for the selected func.
    ///     Additional support will be required in a JIT environment.
    CUresult (CUDAAPI *FunctionGetLaunchConfig)(
        CUfunction func,
        CUtoolsFunctionLaunchConfig *config);
    
    /// \brief Set launch-parameters for the function, such as local-mem size per thread.
    /// These settings will apply on the next launch.
    /// It is appropriate to use this function during these callbacks:
    ///     CU_TOOLS_CBID_LAUNCH_BEFORE_FUNCTION_SETUP  -- set new state
    ///     CU_TOOLS_CBID_LAUNCH_AFTER_LAUNCH_PUSH      -- restore state to normal
    /// TODO: This assumes that ucode exists for the selected func.
    ///     Additional support will be required in a JIT environment.
    CUresult (CUDAAPI *FunctionSetLaunchConfig)(
        CUfunction func,
        const CUtoolsFunctionLaunchConfig *config);

    /// \brief Query the driver for either original or relocated instructions.
    /// Most of the time, relocated will be necessary for debuggers.
    /// \param requestRelocatedInstructions : Boolean.  If non-zero, indicates
    ///     that relocated instructions should be requested.
    /// \param ppInstructions : (*ppInstructions) will point at an instruction
    ///     buffer in sysmem that belongs to the driver.
    /// \param pInstructionSizeInBytes : (*pInstructionSizeInBytes) will contain
    ///     the number of bytes in the instruction buffer.
    /// TODO: This assumes that ucode exists for the selected func.
    ///     Additional support will be required in a JIT environment.
    CUresult (CUDAAPI *FunctionGetInstructions)(
        CUcontext ctx,
        CUfunction func,
        uint32_t requestRelocatedInstructions,
        const void** ppInstructions,
        uint32_t* pInstructionsSizeInBytes);

    /// \brief Get memory-handles for local-mem, CRS-stack-mem, instructions, etc.
    CUresult (CUDAAPI *FunctionGetMemObjHandles)(
        CUfunction func,
        CUtoolsFunctionMemObjHandles* handles);

    /// \brief Retrieve a function's name.
    CUresult (CUDAAPI *FunctionGetName)(
        CUcontext ctx, 
        CUfunction func, 
        const char** ppName);

    /// \brief Find a function by name.
    CUresult (CUDAAPI *FindFunctionByName)(
        CUcontext ctx, 
        CUmodule mod, 
        const char* pName, 
        CUfunction* pFunc);

    /// \brief Invokes the callback for every __global__ function.
    /// \return Returns the number of global functions.
    /// The purpose here is to provide a mapping between name and CUfunction.
    uint32_t (CUDAAPI *ModuleEnumerateGlobalFunctions)(
        CUcontext ctx,
        CUmodule mod,
        CUtoolsEnumerateGlobalFunctionsCallback pfnCallback,
        void* pUserData);

    /// \brief Invokes the callback for every __device__ and __constant__ variable.
    /// \param pfnCallback : if non-null, will be invoked on each global symbol
    /// \param pUserData : like a 'this' pointer, recycled into the callback
    /// \return Returns the number of globals + constants.
    /// __device__ and __constant__ variables have global-memory addresses.
    /// (remember that constants are just cached out of global-memory through
    //   the SM's constant buffers)
    uint32_t (CUDAAPI *ModuleEnumerateGlobalVariables)(
        CUcontext ctx, 
        CUmodule mod,
        CUtoolsEnumerateGlobalVariablesCallback pfnCallback,
        void* pUserData);

    /// \brief Returns the number of bind-able texture slots, or -1 on error.
    uint32_t (CUDAAPI *FunctionGetTexRefCount)(
        CUcontext ctx,
        CUfunction func);
    /// \brief Returns the textureSlot'th texref.
    /// NOTE: The textureSlot is the tidU08 field of the Tesla TEX instruction.
    CUresult (CUDAAPI *FunctionGetTexRefItem)(
        CUcontext ctx,
        CUfunction func,
        uint32_t textureSlot,
        CUtexref* pTexRef);
        
    /// \brief Gets the unique ID for the module.
    /// Module IDs are unique per cubin file (or driver internal modules).
    /// The IDs are linearly increasing for each newly loaded module. 
    /// Unique IDs should be used in place of the CUmodule address as 
    /// multiple addresses can point to the same module.
    /// Note: This does not replace the utility of handles. In short, handles
    ///       enable tracking per module/context pair, while unique IDs allow
    ///       tracking per cubin file, i.e. source code.
    CUresult (CUDAAPI *ModuleGetId)(
        CUmodule mod,
        uint32_t* pModuleId);
        
    /// \brief Gets the unique ID for the function.
    /// Function IDs are unique across cubin files (or driver internal modules).
    /// The ID is build by (moduleID<<32 + order of functions in the module).
    /// Unique IDs should be used in place of the CUfunc address as 
    /// multiple address can point to the same function.
    /// Note: This does not replace the utility of handles. In short, handles
    ///       enable tracking per module/context pair, while unique IDs allow
    ///       tracking per cubin file, i.e. source code.
    CUresult (CUDAAPI *FunctionGetId)(
        CUfunction func,
        uint32_t* pFunctionId);

    /// \brief Gets the memobj containing this function
    CUresult (CUDAAPI *FunctionGetInstructionsMemObj)(
        CUfunction func,
        CUtoolsMemObjHandle* phMemObjInstructions);

    /// \brief Get the current value of %gridId.
    /// \deprecated Use FunctionGetGridId64
    ///
    /// %gridId width is architecture dependent.
    ///   Tesla:    only the lower 16-bits are available
    ///   Fermi:    only the lower 32-bits are available
    ///   Kepler+:  the full 64-bits are available
    ///
    /// *pGridId will always be returned as a 32-bit value. The caller should
    /// truncate based upon architecture in order to match %gridId.
    ///
    /// This function can be called during CU_TOOLS_CB_DOMAIN_LAUNCH callbacks.
    /// Calling this function outside of launch callbacks has undefined
    /// behavior.
    CUresult (CUDAAPI *FunctionGetGridId)(
        uint32_t *pGridId,
        CUfunction func);

    /// Outputs sizes of param-blocks uploaded to both shared and constant memory.
    void (CUDAAPI *FunctionGetParamsSizes)(
        CUfunction func,
        size_t* pSharedSize,
        size_t* pConstSize);

    /// Write the param-block contents into the memory pointed at by pSharedDest, pConstDest.
    void (CUDAAPI *FunctionGetParamBlockData)(
        CUfunction func, 
        void* pSharedDest,
        size_t sharedDestSize,
        void* pConstDest,
        size_t constDestSize);

    CUresult (CUDAAPI *FunctionGetCacheConfig)(
        CUfunction func,
        int32_t *pConfig);

    CUresult (CUDAAPI *FunctionSetCacheConfig)(
        CUfunction func,
        int32_t config);

    CUresult (CUDAAPI *FunctionGetAttribute)(
        CUfunction func,
        int32_t attrib,
        int32_t *pParam);

    /// \brief sets a debugger parameter for a function
    /// Custom parameters are used for binary patching. They work like normal parameters but are on a different
    /// constant bank (debugger constant bank). To use them, do the following:
    ///  1. On patching time (i.e. OnModuleLoaded) use FunctionGetDebuggerParamsConstantBankInfo to change all constant bank accesses
    ///  2. Before launching (i.e. OnBeforeFunctionSetup)
    ///   2.1. set the needed size for debugger parameters using FunctionSetDebuggerParamsSize
    ///   2.2. set the parameter values using FunctionSetDebuggerParams
    CUresult (CUDAAPI *FunctionSetDebuggerParams)(
        CUfunction func, 
        size_t offsetInBytes,
        const void* params,
        size_t paramsSizeInBytes);

    /// \brief gets a debugger parameter
    /// \sa FunctionSetDebuggerParams
    CUresult (CUDAAPI *FunctionGetDebuggerParams)(
        CUfunction func, 
        size_t offsetInBytes, 
        void *params,
        size_t paramsSizeInBytes);

    /// \brief sets the size for debugger parameters for a given function
    /// \sa FunctionSetDebuggerParams
    /// The specified size will be allocated for the cuFunction. 
    /// If there was another SetSize before with at least the same size, the function will only set an internal attribute 
    //  to avoid malloc/free overhead if bForceAllocation is false.
    /// So one performance optimization is to call the function OnModuleLoad time with an estimate for the needed size.
    CUresult (CUDAAPI *FunctionSetDebuggerParamsSize)(
        CUfunction func,
        size_t paramsSizeInBytes,
        uint8_t bForceReallocation
        );

    /// \brief gets the size for debugger parameters
    /// \sa FunctionSetDebuggerParamsSize
    CUresult (CUDAAPI *FunctionGetDebuggerParamsSize)(
        CUfunction func,
        size_t *paramsSizeInBytesUsed,
        size_t *paramsSizeInBytesAllocated);

    /// \brief gets information for access the debugger parameter on runtime
    /// Each opcode which uses the debugger parameter should be changed with the provided info.
    /// For example the standard LDC R0, c[17][4] on Fermi should be LDC R0, c[bankNumber][offsetInBytes + 4] after changing the patch.
    CUresult (CUDAAPI *FunctionGetDebuggerParamsConstantBankInfo)(
        CUfunction func,
        size_t *bankNumber,
        size_t *offsetInBytes,
        size_t *maxBytesAvailable);

    /// \brief sets the flag to force updating debugger const bank on all launches.
    /// Not threadsafe by design, must be set during init.
    CUresult (CUDAAPI *ForceDebuggerConstBankInvalidation)(
        CUcontext ctx,
        uint8_t bForceInvalidation);

    /// \brief gets the module that contains a function
    CUresult (CUDAAPI *FunctionGetModule)(
        CUfunction func,
        CUmodule *pMod);

    /// \brief gets the owner of a module (user or driver).
    /// pOwner points to a CUtoolsModuleOwner enum value.
    CUresult (CUDAAPI *ModuleGetOwner)(
        CUmodule mod,
        uint32_t *pOwner);

    /// \brief Equivalent of cuModuleLoadDataEx.
    CUresult (CUDAAPI *ModuleLoadDataEx)(
        CUcontext ctx,
        CUmodule *phMod,
        const void *p,
        unsigned int numOptions,
        CUjit_option *options,
        void **optionValues);

    /// Calculate lmemHiSize assuming dataStackSize is the only free variable.
    /// It includes the user data-stack, system-stack, and debugger-stack.
    /// dataStackSize can be retrieved from CU_LIMIT_STACK_SIZE to match the user's setting.
    CUresult (CUDAAPI *CalcLMemHiSize)(
        CUcontext ctx,
        uint32_t dataStackSize,
        uint32_t *pLMemHiSize);

    /// Returns minimum LMemHiSize (per thread) required to launch this function.
    /// It includes the user data-stack, system-stack, and debugger-stack.
    CUresult (CUDAAPI *FunctionCalcLMemHiSize)(
        CUfunction func,
        uint32_t *pLMemHiSize);

    /// Calculate size of the chip-wide LMem-allocation assuming lmemLoSize and dataStackSize
    /// are the only free variables.
    /// lmemLoSize is typically controlled by the compiler or the user via the compiler.
    /// dataStackSize can be retrieved from CU_LIMIT_STACK_SIZE to match the user's setting.
    CUresult (CUDAAPI *CalcLMemAllocationSize)(
        CUcontext ctx,
        uint32_t lmemLoSize,
        uint32_t dataStackSize,
        uint32_t *pLMemAllocationSize,
        uint32_t *pIsValid);

    /// Size of the chip-wide LMem-allocation required to launch this function.
    CUresult (CUDAAPI *FunctionCalcLMemAllocationSize)(
        CUfunction func,
        uint32_t *pLMemAllocationSize,
        uint32_t *pIsValid);

    /// Get the number of parameters a kernel takes.
    CUresult (CUDAAPI *FunctionGetParamCount)(
        CUfunction func,
        size_t *pParamCount);

    /// Get information about a kernel parameter.
    CUresult (CUDAAPI *FunctionGetParamInfo)(
        CUfunction func,
        size_t paramIndex,
        CUtoolsKernelParamInfo *pParamInfo);

    /// \brief Extended cuModuleLoadDataEx that takes a ptxas option string (userPtxasOptions)
    CUresult (CUDAAPI *ModuleLoadDataExWithAssemblerOptions)(
        CUcontext ctx,
        CUmodule *phMod,
        const void *p,
        unsigned int numOptions,
        CUjit_option *options,
        void **optionValues,
        char *userPtxasOptions);

    // Get the FunctionMemObjHandles related to a syscall function
    CUresult (CUDAAPI *GetSyscallFuncMemObj)(
        CUcontext ctx,
        const char *funcName,
        CUtoolsMemObjHandle *phMemObj);

    /// \brief Extended cuModuleLoadDataEx that allows the trampolines to be bypassed 
    CUresult (CUDAAPI *ModuleLoadDataExBypassTrampolines)(
        CUcontext ctx,
        CUmodule *phMod,
        const void *p,
        unsigned int numOptions,
        CUjit_option *options,
        void **optionValues);

    /// \brief Get the current value of %gridId.
    ///
    /// %gridId width is architecture dependent.
    ///   Tesla:    only the lower 16-bits are available
    ///   Fermi:    only the lower 32-bits are available
    ///   Kepler+:  the full 64-bits are available
    ///
    /// *pGridId will always be returned as a 64-bit value. The caller should
    /// truncate based upon architecture in order to match %gridId.
    ///
    /// This function can be called during CU_TOOLS_CB_DOMAIN_LAUNCH callbacks.
    /// Calling this function outside of launch callbacks has undefined
    /// behavior.
    CUresult (CUDAAPI *FunctionGetGridId64)(
        uint64_t *pGridId,
        CUfunction func);

    /// Get the current launch PC for a CUfunction.
    /// This corresponds to the value of the program offset that all GPU
    /// threads begin execution on.  For reference here are examples of how
    /// this is programmed to the hardware.
    /// Tesla  : NV50C0_SET_CTA_PROGRAM_START_OFFSET
    /// Fermi  : NV90C0_SET_CTA_PROGRAM_START
    /// Kepler : NVA0C0_QMDV00_06_PROGRAM_OFFSET (in the QMD, not pushbuffer)
    CUresult (CUDAAPI *FunctionGetLaunchPc)(
        CUfunction func,
        uint64_t *outLaunchPc);

    /// Sets the launch PC for a CUfunction.  This is sticky.
    /// It is guaranteed to take effect on the next launch of that CUfunction; the latest
    /// time this may be called is from the CU_TOOLS_CBID_LAUNCH_BEFORE_FUNCTION_SETUP callback.
    /// Calling this function in any of the other launch callbacks is not
    /// guaranteed to apply to the current launch, and should generally be
    /// avoided.
    /// This function may be called from CU_TOOLS_CBID_LAUNCH_AFTER_GRID_LAUNCHED.
    /// That can be useful to restore the CUfunction's launch PC if desired.
    CUresult (CUDAAPI *FunctionSetLaunchPc)(
        CUfunction func,
        uint64_t launchPc);

    /// \brief Retrieve a function's type.
    /// \return Returns CUDA_SUCCESS unless one of the parameters is invalid.
    CUresult (CUDAAPI *FunctionGetType)(
        CUcontext ctx,
        CUfunction func,
        CUtools_function_type *pType);

    /// \brief Invokes the callback for every __global__ and __device__ function.
    /// \return Returns CUDA_SUCCESS unless one of the parameters is invalid.
    /// The callback can query properties of the encountered CUfunctions using
    /// other Tools API functions, such as FunctionGetType.
    CUresult (CUDAAPI *ModuleEnumerateFunctions)(
        CUcontext ctx,
        CUmodule mod,
        CUtoolsEnumerateFunctionsCallback pfnCallback,
        void *pUserData);

    /// \brief Check if cnp is used in the module.
    CUresult (CUDAAPI *ModuleUsesCnp)(
        CUmodule mod,
        CUtools_cnp_support *flag);

    /// \brief Check if cnp is used in the function.
    CUresult (CUDAAPI *FunctionUsesCnp)(
        CUfunction func,
        CUtools_cnp_support *flag);

    /// \brief Check if cnpjoin is used in the function.
    CUresult (CUDAAPI *FunctionUsesCnpJoin)(
        CUfunction func,
        uint32_t *flag);

    /// \brief Same as FunctionSetLaunchConfig() except it also updates the device copy of the state
    /// Note: This function locks the ctx and may issue an inline host to device memcopy
    CUresult (CUDAAPI *FunctionSetLaunchConfigHostAndDevice)(
        CUfunction func,
        const CUtoolsFunctionLaunchConfig *config);

    /// \brief Same as FunctionSetLaunchPc() except it also updates the device copy of the state
    /// Note: This function locks the ctx and may issue an inline host to device memcopy
    CUresult (CUDAAPI *FunctionSetLaunchPcHostAndDevice)(
        CUfunction func,
        uint64_t launchPc);

    /// May be used to modify the %gridId for the next launch.
    /// If called in either of the BEFORE_FUNCTION_SETUP or AFTER_FUNCTION_SETUP callbacks,
    /// it affects the current launch.  Otherwise behavior is undefined.
    /// See FunctionGetGridId64 for more details.
    CUresult (CUDAAPI *FunctionSetGridId64)(
        CUfunction func,
        uint64_t gridId);

    /// \brief Retrieve a context's syscall module.
    CUresult (CUDAAPI *CtxGetSyscallModule)(
        CUcontext ctx,
        CUmodule *pMod);

    /// \brief Retrieve the memobj for a module's constants.
    CUresult (CUDAAPI *ModuleGetConstBankMemObj)(
        CUmodule mod,
        CUtoolsMemObjHandle *phMemObj);

    /// \brief Retrieve info for a module's symbol by name.
    CUresult (CUDAAPI *ModuleGetSymbol)(
        CUmodule mod,
        const char *symbolName,
        uint32_t *pBankNumber,
        CUtoolsMemObjHandle *phMemObj,
        uint32_t *pOffset,
        uint32_t *pSize);

    /// \brief Check if cnp join is used in the module.
    CUresult (CUDAAPI *ModuleUsesCnpJoin)(
        CUmodule mod,
        uint32_t *pFlag);

    /// \brief Get shared memory config of the function
    CUresult (CUDAAPI *FunctionGetSharedMemConfig)(
        CUfunction func,
        int32_t *pConfig);

    /// \brief Get CNP patch state flags of the function
    CUresult (CUDAAPI *FunctionGetCnpPatchInfo)(
        CUfunction func,
        CUtoolsFunctionCnpPatchInfo *pCnpPatchInfo);

    /// \brief Retrieve a function's symbol index.
    CUresult (CUDAAPI *FunctionGetSymbolIndex)(
        CUfunction func, 
        uint64_t *pSymbolIndex);

    /// \brief Find a function by symbol index.
    CUresult (CUDAAPI *FindFunctionBySymbolIndex)(
        CUmodule mod, 
        uint64_t symbolIndex, 
        CUfunction *pFunc);

    CUresult (CUDAAPI *CtxGetSystemStackSize)(
        CUcontext ctx,
        uint32_t *systemStackSize);

    CUresult (CUDAAPI *CtxSetSystemStackSize)(
        CUcontext ctx,
        uint32_t newSystemStackSize);

    /// \brief Wrapper of function cuiFuncDownloadEx.
    /// This function isolate the profiler for making any change in 
    /// its code if cuifuncDownloadEx changes its implementation.
    /// \param hMemObjDest corresponds to the destination memobj.
    /// \param pSource does not need to be pinned (pageable is OK)
    /// \param copySizeInBytes number of bytes to transfer
    CUresult (CUDAAPI *FunctionDownload)(
        CUcontext ctx,
        CUtoolsStreamHandle stream,
        CUtoolsMemObjHandle hMemObjDest,
        size_t destOffset,
        const void *pSource,
        size_t copySizeInBytes);

    CUresult (CUDAAPI *FunctionGetCodeSize)(
        CUfunction func,
        size_t *pCodeSize);

    /// \brief Equivalent of cuModuleUnload.
    CUresult (CUDAAPI *ModuleUnload)(
        CUmodule mod);

    /// \brief Retrieve the ELF image and its size for a loaded module
    CUresult (CUDAAPI *ModuleGetImage)(
        CUmodule mod,
        void **pImage,
        size_t *pImageSize);

    /// \brief Retrieve the context of a loaded module
    CUresult (CUDAAPI *ModuleGetContext)(
        CUmodule mod,
        CUcontext *pCtx);

    // Check if a function is hidden
    CUresult (CUDAAPI *FunctionIsHidden)(
        CUfunction func,
        uint8_t *isHidden);

} CUetblToolsModule;


#ifdef __cplusplus
}
#endif // __cplusplus

#endif // file guard
