/*
 * Copyright 1993-2014 NVIDIA Corporation.  All rights reserved.
 *
 * NOTICE TO LICENSEE:
 *
 * This source code and/or documentation ("Licensed Deliverables") are
 * subject to NVIDIA intellectual property rights under U.S. and
 * international Copyright laws.
 *
 * These Licensed Deliverables contained herein is PROPRIETARY and
 * CONFIDENTIAL to NVIDIA and is being provided under the terms and
 * conditions of a form of NVIDIA software license agreement by and
 * between NVIDIA and Licensee ("License Agreement") or electronically
 * accepted by Licensee.  Notwithstanding any terms or conditions to
 * the contrary in the License Agreement, reproduction or disclosure
 * of the Licensed Deliverables to any third party without the express
 * written consent of NVIDIA is prohibited.
 *
 * NOTWITHSTANDING ANY TERMS OR CONDITIONS TO THE CONTRARY IN THE
 * LICENSE AGREEMENT, NVIDIA MAKES NO REPRESENTATION ABOUT THE
 * SUITABILITY OF THESE LICENSED DELIVERABLES FOR ANY PURPOSE.  IT IS
 * PROVIDED "AS IS" WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND.
 * NVIDIA DISCLAIMS ALL WARRANTIES WITH REGARD TO THESE LICENSED
 * DELIVERABLES, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY,
 * NONINFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE.
 * NOTWITHSTANDING ANY TERMS OR CONDITIONS TO THE CONTRARY IN THE
 * LICENSE AGREEMENT, IN NO EVENT SHALL NVIDIA BE LIABLE FOR ANY
 * SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, OR ANY
 * DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS
 * ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
 * OF THESE LICENSED DELIVERABLES.
 *
 * U.S. Government End Users.  These Licensed Deliverables are a
 * "commercial item" as that term is defined at 48 C.F.R. 2.101 (OCT
 * 1995), consisting of "commercial computer software" and "commercial
 * computer software documentation" as such terms are used in 48
 * C.F.R. 12.212 (SEPT 1995) and is provided to the U.S. Government
 * only as a commercial end item.  Consistent with 48 C.F.R.12.212 and
 * 48 C.F.R. 227.7202-1 through 227.7202-4 (JUNE 1995), all
 * U.S. Government End Users acquire the Licensed Deliverables with
 * only those rights set forth herein.
 *
 * Any use of the Licensed Deliverables in individual and commercial
 * software must include, in the user documentation and internal
 * comments to the code, the above Disclaimer and U.S. Government End
 * Users Notice.
 */

// ----------------------------------------------------------------------------
// 
// Private header file for the CompUte Device Api
//      This header contains CUDA functionality not intended for public
//      consumption.
//
// ----------------------------------------------------------------------------

#ifndef __cuda_cuda_private_h__
#define __cuda_cuda_private_h__

#include <stdlib.h>
#include "cuda.h"

#ifdef __cplusplus
extern "C" {
#endif

    // PTX module loading
    // phMod, ptx, fname must be non-null.
    // ptxasOptions defaults to ' ' if NULL
    CUresult CUDAAPI cuModuleLoadDataPtx( CUmodule *phMod, void *ptx, char *ptxasOptions );
    CUresult CUDAAPI cuModuleLoadPtx( CUmodule *phMod, const char *fname, char *ptxasOptions );

#if defined(__ANDROID__)
    // Ptx Compilation API to be used by Renderscript compiler
    // Compiles a ptx to cubin
    CUresult CUDAAPI cuPvtCompilePtx(void** cubin, size_t *cubinSize, const void *image, unsigned int numOptions, CUjit_option *options, void **optionValues);
    // API to free cubin generated by cuCompilePtx
    CUresult CUDAAPI cuPvtBinaryFree(void* cubin);
#endif
    // Surface reference API
    // keeping some of the as-yet-deprecated functions in cuda_private.h

    CUresult  CUDAAPI cuSurfRefSetAddress( unsigned int *ByteOffset, CUsurfref hSurfRef, unsigned int dptr, unsigned int bytes );
    CUresult  CUDAAPI cuSurfRefGetAddress( unsigned int *pdptr, CUsurfref hSurfRef );

    CUresult  CUDAAPI cuParamSetSurfRef(CUfunction func, int surfunit, const char *name, CUsurfref hSurfRef);


    CUresult CUDAAPI cuMemMap(void **ret, unsigned int ptr);
    CUresult CUDAAPI cuMemUnmap(const void *ptr);

// System memory arrays now private

    //
    // residence flags
    //
        #define CU_AD_RESIDENCE_SYSTEM      0x01
        #define CU_AD_RESIDENCE_DEVICE      0x02

    //
    // access flags
    //
        #define CU_ACCESS_READ      0x01
        #define CU_ACCESS_WRITE     0x02

    // map for CPU access
    CUresult  CUDAAPI cuArrayMap( void **ppOut, int *pPitch, CUarray hArray );
    CUresult  CUDAAPI cuArrayFromMapping(CUarray *phArray , void *p);
    CUresult  CUDAAPI cuArrayUnmap( CUarray hArray );

    // system memory texturing (1D buffer)
    CUresult  CUDAAPI cuTexRefSetCPUAddress( CUtexref hTexRef, const void *base, int bytes );

    /************************************
     **
     **     Array format macros
     **
     ************************************/

#define CUARRAY_FORMAT_SHIFT  0
#define CUARRAY_FORMAT_MASK   ((0xff)<<CUARRAY_FORMAT_SHIFT)

#define GET_CUARRAY_FORMAT(a)  ((a) & CUARRAY_FORMAT_MASK)

/**
 * Memory attributes
 */
typedef enum CUmem_attribute_enum {
    CU_MEM_ATTRIBUTE_PHYSICAL_ADDRESS=1,
    CU_MEM_ATTRIBUTE_PTE_KIND,
    CU_MEM_ATTRIBUTE_PARTITION_STRIDE,
    CU_MEM_ATTRIBUTE_LAST
} CUmem_attribute;

    CUresult CUDAAPI cuMemGetAttribute(unsigned int dptr, unsigned long long *pi, CUmem_attribute attribute);
    CUresult CUDAAPI cuMemGetAttribute_v2(CUdeviceptr dptr, unsigned long long *pi, CUmem_attribute attribute);

#define CU_TRSF_MISALIGNED_VIDEO_8BPP   0x04
#define CU_TRSF_PACK_COMPONENTS         0x08

typedef enum CUIjitOperationType_enum {
    CUI_JIT_OP_COMPILER = 0,
    CUI_JIT_OP_LINKER
} CUIjitOperationType;

typedef struct CUIjitStatistic_st {
    const char *description;
    CUIjitOperationType type;
    float wallTime;
    unsigned int endingInfoLogBufferPosition;
    unsigned int endingErrorLogBufferPosition;
} CUIjitStatistic;

#define CU_JIT_OPTIONS_INTERNAL_START 10000

typedef enum CUjit_option_internal_enum {
    /**
     * Specifies an array of CUIjitStatistic to gather data about
     * JIT operations.
     * Value type: CUIjitStatistic *
     */
    CU_JIT_STATISTICS = CU_JIT_OPTIONS_INTERNAL_START,

    /**
     * For use with ::CU_JIT_STATISTICS
     * In: size of statistics array
     * Out: number of slots which would be used with a large enough
     *   array.  This may be larger than the array size, in which
     *   case the output was truncated.
     * Value type: unsigned int
     */
    CU_JIT_STATISTICS_SIZE,

    /**
     * Specify the knob values to pass to the jit as a comma
     * separated list, free of spaces, or no knob option if NULL.
     *
     * **WARNING: API maintains pointer to caller-supplied string
     *            between cuLinkCreate() and cuLinkDestroy(),
     *            so do not modify or free the associated string
     *            memory between these calls.
     *
     * E.g. setting this option value to:
     *     "knobFoo=13,knobBar=37"
     * will pass the following to ptxas:
     *     "--knob knobFoo=13,knobBar=37".
     * Set to NULL to remove an existing cuLinkCreate() setting
     * for a specific call to cuLinkAddData() or cuLinkAddFile().
     * Will error if value contains erroneous whitespace.
     * Value type: const char *
     */
    CU_JIT_KNOB,

    CU_JIT_OPTIONS_INTERNAL_MAX
} CUjit_option_internal;

#define CU_JIT_NUM_INTERNAL_OPTIONS (CU_JIT_OPTIONS_INTERNAL_MAX - CU_JIT_OPTIONS_INTERNAL_START)

#ifdef __cplusplus
}
#endif

#endif /* __cuda_cuda_private_h__ */
