#!/bin/bash

#SBATCH -p luna
#SBATCH -A coreai_libraries_nccl
#SBATCH -N 8                                     # number of nodes
#SBATCH -t 01:00:00                              # wall time
#SBATCH -J "coreai_libraries_nccl-bisection:8x8" # job name
##SBATCH --exclusive                             # exclusive node access
#SBATCH --mem=0                                  # all mem avail
##SBATCH --mail-type=FAIL                        # only send email on failure
#SBATCH --ntasks-per-node=8                      # max 8 tasks per machine (one task per gpu) - Exception for pytorch // srun launch with -n1
##SBATCH --threads-per-core=2                    # HT is on
#SBATCH --output=%x_%j.out
#SBATCH --comment=sysctl-sys.kernel.numa_balancing=0,transparent_hugepage_defrag=never,transparent_hugepage=never

# This script is an example of using selene to test a bisection to find a perf regressoin

set +e

# Env
export CUDA_HOME=/project/nccl/toolkits/cuda-11.8
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
export NVCC_GENCODE="-gencode=arch=compute_80,code=sm_80"
export MPI_HOME=/usr/mpi/gcc/openmpi-4.1.2a1
export LD_LIBRARY_PATH=$MPI_HOME/lib:$LD_LIBRARY_PATH
export PATH=$MPI_HOME/bin:$PATH
export NCCL_IB_SL="1"
export OMPI_MCA_btl="^openib"
export OMPI_MCA_btl_tcp_if_include="enp97s0f1"
export NCCL_DEBUG=WARN

# Change these as you like
REPRO="alltoall_perf -d half -b4M -e4M -w5 -n20 -f2"
final_commit="v2.18.3-1"
initial_commit="v2.17.1-1"
iterations=5
threshold=25
ONLY_FUNCS="SendRecv"
NCCL_TMP_DIR=/lustre/fsw/nccl/bewilliams
NCCL_SRC_DIR=~/nccl

# Set to 1 if you are resuming a cancelled bisection
load_checkpoint=0

~/nccl/test/scripts/bisection.sh $initial_commit $final_commit "$REPRO" $threshold "$ONLY_FUNCS" $iterations $NCCL_TMP_DIR $NCCL_SRC_DIR $load_checkpoint
