LIBROOT=/usr/local/cuda

export CUDA=$LIBROOT
export CUDA_HOME=$CUDA
export PATH=$LIBROOT/bin:$PATH
export C_INCLUDE_PATH=$LIBROOT/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$LIBROOT/include:$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH=$LIBROOT/lib64:$LD_LIBRARY_PATH
export LIBRARY_PATH=$LIBROOT/lib64:$LIBRARY_PATH
