#!/bin/bash

#SBATCH -p backfill_block2
#SBATCH -A coreai_libraries_nccl
#SBATCH -N 4                      # number of nodes
# NOTE - there is a higher init time on draco-oci than usual
#SBATCH -t 00:15:00               # wall time
#SBATCH -J "coreai_libraries_nccl-job-name:4x8"     # job name, you can change according to purpose + dimensions
#SBATCH --mem=0                   # all mem avail
#SBATCH  --gpus-per-node=8        # Must ask for gpus-per-node on draco
#SBATCH --ntasks-per-node=8       # max 8 tasks per machine (one task per gpu) - Exception for pytorch // srun launch with -n1
#SBATCH --output=%x_%j.out
#SBATCH --comment=sysctl-sys.kernel.numa_balancing=0,transparent_hugepage_defrag=never,transparent_hugepage=never

set +e

# Env
module add openmpi4/gcc/4.1.5
export CUDA_HOME=~/cuda-12.3.69-20230929
export CUDA_MAJOR=12
export CUDA_MINOR=3
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
export NVCC_GENCODE="-gencode=arch=compute_80,code=sm_80"
export MPI_HOME=/cm/shared/apps/openmpi4/gcc/4.1.5
export LD_LIBRARY_PATH=$MPI_HOME/lib:$LD_LIBRARY_PATH
export NCCL_IB_SL="1"
export OMPI_MCA_btl="^openib"
export OMPI_MCA_btl_tcp_if_include="eth0" #eth0 is the ifname for tcp
export NCCL_DEBUG=WARN

date

squeue -u $USER

export NCCL_HOME=~/nccl/build
# Uncomment if you want to rebuild nccl
#pushd ~/nccl
#make clean
#make -j test.build MPI=1 TRACE=1
#popd

# How to use srun / mpirun

echo "CASE: 1 srun pmix"
srun --mpi=pmix $NCCL_HOME/test/perf/alltoall_perf -b8 -e1G -f2

echo "CASE: 2 mpirun"
mpirun -output-filename ~/my-output --bind-to numa $NCCL_HOME/test/perf/alltoall_perf -b8 -e1G -f2
