#!/bin/bash

#SBATCH -p batch
#SBATCH -A coreai_libraries_nccl
#SBATCH -N 2
#SBATCH -t 10
#SBATCH -J coreai_libraries_nccl-perftests:2x8
#SBATCH --mem=0
#SBATCH --ntasks-per-node=8
#SBATCH --output=%x_%j.out
#SBATCH --comment=sysctl-sys.kernel.numa_balancing=0,transparent_hugepage_defrag=never,transparent_hugepage=never

set +e

# Bring your own CUDA on eos
export CUDA_HOME=~/cuda-12.3.69-20230929
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
export NVCC_GENCODE="-gencode=arch=compute_90,code=sm_90"
export NCCL_HOME=~/nccl/build
export LD_LIBRARY_PATH=$NCCL_HOME/lib:$LD_LIBRARY_PATH
export MPI_HOME=/usr/mpi/gcc/openmpi-4.1.5rc2/
export LD_LIBRARY_PATH=$MPI_HOME/lib:$LD_LIBRARY_PATH
export PATH=$MPI_HOME/bin:$PATH

# Needed for multinode runs
export NCCL_IB_SL="1"
export OMPI_MCA_btl="tcp,self"
export OMPI_MCA_btl_tcp_if_include="eth3"

#pushd ~/nccl
#make clean
#make -j
#popd
#pushd ~/nccl-tests
#make -j MPI=1
#popd

echo "CASE: 1 baremetal alltoall"
mpirun --oversubscribe ./nccl-tests/build/reduce_scatter_perf -b128K -e16G -f2

# TODO - update your enroot credentials
# Define which container you want to run here
# You can build a container off your branch from https://gitlab-master.nvidia.com/nccl/nccl-container
# Defining a container mount is good if you need to export large outputs from this container, like an NVTX trace
export CONT_NVTX_PROXY="gitlab-master.nvidia.com/nccl/nccl-container/pytorch:master-py3-devel-nccl-2.19.1-1-proxy-nvtx-66a4db23"
echo "CASE: 2 container"
srun --mpi=pmix --container-image="${CONT_NVTX_PROXY}" --container-mounts="/lustre/fsw/coreai_libraries_nccl/<username>/proxy-traces:/workspace/proxy-traces2" --container-name="nccl-container" sh -c "nsys profile -o /workspace/proxy-traces2/%h.%p.trace --force-overwrite true -t cuda,nvtx alltoall_perf_mpi -b 1K -e 8K -f 2 -d half"
