/*************************************************************************
 * Copyright (c) 2016-2020, NVIDIA CORPORATION. All rights reserved.
 *
 * See LICENSE.txt for license information
 ************************************************************************/

#include "comm.h"
#include "info.h"
#include "graph.h"
#include "collectives.h"
#include <assert.h>

enum { proxyRecv=0, proxySend=1 };

static bool NeedProxy(int type, int pattern, int root, struct ncclRing* ring, int nranks) {
  if (pattern == ncclPatternRing || pattern == ncclPatternRingTwice) return true;

  /* In chains, one rank does not need a proxy. Let's figure out which one it is */
  // Which index in the reorganized rings should we compare root against */
  const int myrank = 0, nextrank = 1, prevrank = nranks-1;
  int index = pattern == ncclPatternPipelineFrom ?
      /*                            no recv /  no send    if root = */
      /* bcast  */ (type == proxyRecv ?   myrank : nextrank ):
      /* reduce */ (type == proxyRecv ? prevrank :   myrank );
  int rank = ring->userRanks[index];
  return (root != rank);
}

#define PROXYARGS_ALLOCATE_SIZE 128
struct ncclProxyPool {
  struct ncclProxyPool *next;
  struct ncclProxyArgs elems[PROXYARGS_ALLOCATE_SIZE];
};

static ncclResult_t allocateArgs(struct ncclComm* comm, struct ncclProxyArgs** argsptr) {
  struct ncclProxyState* state = &comm->proxyState;
  struct ncclProxyArgs* elem;
  pthread_mutex_lock(&state->poolMutex);
  if (state->pool == NULL) {
    // Allocate a new pool of elements
    struct ncclProxyPool* newPool;
    NCCLCHECK(ncclCalloc(&newPool, 1));
    struct ncclProxyArgs* newElems = newPool->elems;
    // Chain newly allocated elements
    for (int i=0; i<PROXYARGS_ALLOCATE_SIZE; i++) {
      if (i+1 < PROXYARGS_ALLOCATE_SIZE) newElems[i].next = newElems+i+1;
    }
    // Add them all to the pool list
    state->pool = newElems;
    // Save the pool memory block for later resource release
    newPool->next = state->pools;
    state->pools = newPool;
  }
  elem = state->pool;
  state->pool = state->pool->next;
  pthread_mutex_unlock(&state->poolMutex);
  elem->next = elem->nextPeer = NULL;
  *argsptr = elem;
  return ncclSuccess;
}

//#define PROFILE_PROXY 1
#define TYPE_SEND 0
#define TYPE_RECV 1
#define TYPE_SLEEP 2
#define TYPE_WAKEUP 3
#define TYPE_IDLE 4
#define TYPE_APPEND 5
#define TYPE_APPEND_END 6
#ifdef PROFILE_PROXY
struct ncclProxyProfile {
  void* op;
  uint64_t opCount;
  uint16_t channel;
  uint8_t segment;
  uint8_t type;
  uint32_t state;
  uint64_t timestamp;
  uint64_t posted, received, transmitted, done, end;
};

struct ncclProxyProfile* profilingEvents = NULL;
int profilingIndex = 0;
uint64_t profilingStart = 0;
uint64_t cyclesPerUsec = 0;
#define MAX_EVENTS 200000

static inline uint64_t gettime() {
  uint32_t a, d;
  __asm__ volatile("rdtsc":"=a"(a), "=d"(d));
  return (((uint64_t)d) << 32) | a;
}
#include <unistd.h>
ncclResult_t profilingRecord(struct ncclProxyArgs* op, int type) {
  if (profilingEvents == NULL) {
    NCCLCHECK(ncclCalloc(&profilingEvents, MAX_EVENTS));
    uint64_t time = gettime();
    usleep(100000);
    time = gettime() - time;
    cyclesPerUsec = time/100000;
  }
  // Skip first sleep/wakeup
  if (profilingStart == 0) {
    if (op == NULL && type == TYPE_WAKEUP) profilingStart = gettime();
    return ncclSuccess;
  }
  if (profilingIndex == MAX_EVENTS) return ncclSuccess;
  if (op == NULL) {
    struct ncclProxyProfile* event = profilingEvents+profilingIndex++;
    event->timestamp = gettime()-profilingStart;
    event->op = op;
    event->type = type;
    event->channel = MAXCHANNELS;
    return ncclSuccess; // Proxy Sleep event
  }
  for (int s = 0; s<op->nsubs; s++) {
    if (profilingIndex == MAX_EVENTS) return ncclSuccess;
    struct ncclProxyProfile* event = profilingEvents+profilingIndex++;
    event->timestamp = gettime()-profilingStart;
    event->op = op;
    event->type = type;
    event->state = op->state;
    event->channel = op->subs[s].channel->id;
    event->segment = s;
    event->opCount = op->opCount;
    event->type = op->subs[s].sendbytes ? TYPE_SEND : TYPE_RECV;
    event->posted = op->subs[s].posted;
    event->received = op->subs[s].received;
    event->transmitted = op->subs[s].transmitted;
    event->done = op->subs[s].done;
    event->end = op->subs[s].nsteps;
  }
  return ncclSuccess;
}

const char* figHeader = "#FIG 3.2 Generated by NCCL\nLandscape\nCenter\nMetric\nA4\n100.00\nSingle\n-2\n1200 2\n";

#define FIG_TICK 100
void figLine(FILE* f, uint64_t start, uint64_t oldVal, uint64_t newVal, int x, int y, int color) {
  if (oldVal == newVal) return;
  int y0 = y + (oldVal-start)*FIG_TICK;
  int y1 = y + (newVal-start)*FIG_TICK;
  fprintf(f, "2 1 0 1 %d 7 40 -1 -1 0.000 0 0 -1 0 0 2\n\t  %d %d  %d %d\n", color, x, y0, x, y1);
}

void profilingDump() {
  const char* str = getenv("NCCL_PROXY_PROFILE");
  if (!str) { free(profilingEvents); return; }
  FILE* f = fopen(str, "w");
  fprintf(f, "%s", figHeader);
  int cyclesFactor = cyclesPerUsec/10;

  int maxSize = 40, maxChannel = 0;
  for (int i=0; i<profilingIndex; i++) {
    struct ncclProxyProfile* e = profilingEvents+i;
    if (e->end-e->done > maxSize) maxSize = e->end-e->done;
    if (e->op != NULL && e->channel >= maxChannel) maxChannel = e->channel+1;
  }
  int yMax = FIG_TICK*(10+maxChannel*2*(4+maxSize));

  // Background sleep/wakeup/idle
  int x = 0;
  int xSleep = 0, xAppend = 0;
  for (int i=0; i<profilingIndex; i++) {
    if (profilingEvents[i].op == NULL && profilingEvents[i].channel == MAXCHANNELS) {
      struct ncclProxyProfile* e = profilingEvents+i;
      x = e->timestamp/cyclesFactor;
      if (e->type == TYPE_SLEEP) xSleep = x;
      else if (e->type == TYPE_APPEND) xAppend = x;
      else if (e->type == TYPE_WAKEUP) {
        fprintf(f, "2 2 0 0 0 29 50 -1 20 0.000 0 0 -1 0 0 5\n\t  %d %d  %d %d  %d %d  %d %d  %d %d\n", xSleep, 500, x, 500, x, yMax, xSleep, yMax, xSleep, 500);
      } else if (e->type == TYPE_IDLE) {
        fprintf(f, "2 1 0 1 30 7 50 -1 20 0.000 0 0 -1 0 0 2\n\t  %d %d  %d %d\n", x, 500, x, yMax);
      } else if (e->type == TYPE_APPEND_END) {
        fprintf(f, "2 2 0 0 0 12 48 -1 20 0.000 0 0 -1 0 0 5\n\t  %d %d  %d %d  %d %d  %d %d  %d %d\n", xAppend, 500, x, 500, x, yMax, xAppend, yMax, xAppend, 500);
      }
    }
  }
  // Time axis
  fprintf(f, "2 1 0 1 0 7 50 -1 -1 0.000 0 0 -1 0 0 2\n\t  0 500 %d 500\n", x);
  for (int t=100; t<x; t+=100) {
    if (t % 1000 == 0) {
      fprintf(f, "4 0 0 50 -1 0 12 0.0000 4 135 90 %d 320 %.1f ms\\001\n", t-250, ((float)t)/10000);
      fprintf(f, "2 1 0 1 0 7 50 -1 -1 0.000 0 0 -1 0 0 2\n\t  %d 400 %d 600\n", t, t);
    } else {
      fprintf(f, "2 1 0 1 0 7 50 -1 -1 0.000 0 0 -1 0 0 2\n\t  %d 450 %d 550\n", t, t);
    }
  }

  // Communication requests
  for (int i=0; i<profilingIndex; i++) {
    void* op = profilingEvents[i].op;
    if (op == NULL) continue;
    struct {
      uint64_t start = 0, posted = 0, received = 0, transmitted = 0, done = 0, end = 0;
      int x = 0, y = 0, x2 = 0;
    } states[32];
    for (int a=i; a<profilingIndex; a++) {
      struct ncclProxyProfile* e = profilingEvents+a;
      if (e->op != op) continue;
      states[e->segment].x2 = e->timestamp/cyclesFactor;
      if (e->state == ncclProxyOpReady) {
        if (states[e->segment].end != 0) printf("Error : op %p restarting at index %d\n", op, a);
        states[e->segment].x = e->timestamp/cyclesFactor;
        states[e->segment].y = FIG_TICK*(10+(e->channel*2+e->type)*(4+maxSize)+e->segment*4);
      } else if (e->state == ncclProxyOpNone) {
        int x = states[e->segment].x, y = states[e->segment].y, x2 = states[e->segment].x2;
        int y2 = y+(states[e->segment].end-states[e->segment].start)*FIG_TICK;
        fprintf(f, "2 2 0 1 0 7 30 -1 -1 0.000 0 0 -1 0 0 5\n\t  %d %d  %d %d  %d %d  %d %d  %d %d\n", x, y, x, y2, x2, y2, x2, y, x, y);
        fprintf(f, "4 0 0 30 -1 0 12 0.0000 4 135 90 %d %d %c %d/%d/%ld\\001\n", x, y2+2*FIG_TICK, e->type == TYPE_SEND ? 'S' : 'R', e->channel, e->segment, e->opCount);
        states[e->segment].start = states[e->segment].posted = states[e->segment].received = states[e->segment].transmitted = states[e->segment].done = states[e->segment].end =
        states[e->segment].x = states[e->segment].y = states[e->segment].x2 = 0;
      } else {
        if (states[e->segment].end == 0) {
          states[e->segment].start = e->done;
          states[e->segment].posted = e->posted;
          states[e->segment].received = e->received;
          states[e->segment].transmitted = e->transmitted;
          states[e->segment].done = e->done;
          states[e->segment].end = e->end;
        }
        int y = states[e->segment].y, x2 = states[e->segment].x2;
        figLine(f, states[e->segment].start, states[e->segment].posted, e->posted, x2, y, 1);
        states[e->segment].posted = e->posted;
        figLine(f, states[e->segment].start, states[e->segment].received, e->received, x2, y, 20);
        states[e->segment].received = e->received;
        figLine(f, states[e->segment].start, states[e->segment].transmitted, e->transmitted, x2, y, 21);
        states[e->segment].transmitted = e->transmitted;
        figLine(f, states[e->segment].start, states[e->segment].done, e->done, x2, y, 12);
        states[e->segment].done = e->done;
      }
      e->op = NULL;
    }
  }
  fclose(f);
  free(profilingEvents);
}
#else
ncclResult_t profilingRecord(struct ncclProxyArgs* op, int type) { return ncclSuccess; }
void profilingDump() {}
#endif

//#define DEBUG_PROXY 1
#ifdef DEBUG_PROXY
#define DEBUG_PROXY_PRINT printf
#else
#define DEBUG_PROXY_PRINT(...)
#endif

#define OP_INDEX(op) ((op) ? (op)-state->pools->elems : -1)
#define OP_SEEN 0x100000
ncclResult_t dumpProxyState(struct ncclProxyState* state) {
#ifdef DEBUG_PROXY
  struct ncclProxyArgs* op = state->ops;
  while (op) {
    if (op->idle & OP_SEEN) {
      WARN("Active list loop at element %ld", OP_INDEX(op));
    }
    op->idle |= OP_SEEN;
    printf("[%ld(%ld/%d)]", OP_INDEX(op), op->opCount, op->nsubs);
    if (op->nextPeer) {
      printf("(%ld)", OP_INDEX(op->nextPeer));
      struct ncclProxyArgs* n = op->nextPeer;
      n->idle |= OP_SEEN;
      while (n->nextPeer) {
        n = n->nextPeer;
        n->idle |= OP_SEEN;
      }
    }
    printf("->");
    op = op->next;
  }
  printf("[X]\n");

  struct ncclProxyArgs* free = state->pool;
  while (free) {
    if (free->idle & OP_SEEN) {
      WARN("Free list loop at element %ld", OP_INDEX(free));
    }
    free->idle |= OP_SEEN;
    free = free->next;
  }

  struct ncclProxyPool* p = state->pools;
  int i = 0;
  while (p) {
    for (int e=0; e<PROXYARGS_ALLOCATE_SIZE; e++) {
      if ((p->elems[e].idle & OP_SEEN) == 0) {
        WARN("Element %d of pool %d has been lost", e, i);
        struct ncclProxyArgs* free = state->pool;
        printf("Free list ");
        while (free) {
          printf("--> %ld ", OP_INDEX(free));
          free = free->next;
        }
        printf("\n");
        return ncclInternalError;
      }
      p->elems[e].idle -= OP_SEEN;
    }
    p = p->next;
    i++;
  }
#endif
  return ncclSuccess;
}

static ncclResult_t ProxyAppend(struct ncclProxyState* state, struct ncclProxyArgs* args) {
  struct ncclProxyArgs* proxyAppend = *args->proxyAppendPtr;
  int shared = args->subs[0].connector->conn.shared;
  if (proxyAppend) {
    if (shared && proxyAppend->opCount == args->opCount) {
      assert(proxyAppend->sliceSteps == args->sliceSteps);
      assert(proxyAppend->chunkSteps == args->chunkSteps);
      assert(proxyAppend->protocol == args->protocol);
      assert(proxyAppend->dtype == args->dtype);
      assert(proxyAppend->redOp == args->redOp);
      memcpy(proxyAppend->subs+proxyAppend->nsubs, args->subs, sizeof(struct ncclProxySubArgs));
      proxyAppend->nsubs++;
      args->next = proxyAppend->next;
      // Free args as we merged them
      args->next = state->pool;
      state->pool = args;
      DEBUG_PROXY_PRINT("Insert  %5ld (%d/%5ld/%5ld) as group with %5ld\n", OP_INDEX(args), shared, proxyAppend->opCount, args->opCount, OP_INDEX(proxyAppend));
    } else {
      proxyAppend->nextPeer = args;
      DEBUG_PROXY_PRINT("Insert  %5ld (%d/%5ld/%5ld) as nextPeer of %5ld\n", OP_INDEX(args), shared, proxyAppend->opCount, args->opCount, OP_INDEX(proxyAppend));
      *(args->proxyAppendPtr) = args;
    }
  } else {
    // Nothing running for that peer. Add to the list
    if (state->ops == NULL) {
      // Create the list
      DEBUG_PROXY_PRINT("Insert  %5ld (%d/%5ld) as first element\n", OP_INDEX(args), shared, args->opCount);
      state->ops = args;
    } else {
      // Append element at the end of the list
      struct ncclProxyArgs* last = state->ops;
      while (last->next) last = last->next;
      last->next = args;
      DEBUG_PROXY_PRINT("Insert  %5ld (%d/%5ld) as last element\n", OP_INDEX(args),shared, args->opCount);
    }
    *(args->proxyAppendPtr) = args;
  }
  return ncclSuccess;
}

static ncclResult_t SaveProxy(int type, int peer, struct ncclProxyArgs* args, int connIndex) {
  if (peer < 0) return ncclSuccess;

  struct ncclChannel* channel = args->subs[0].channel;
  struct ncclPeer* peerComm = channel->peers+peer;
  struct ncclConnector* connector = type == proxyRecv ? peerComm->recv+connIndex : peerComm->send+connIndex;
  if (connector->transportComm == NULL) {
    WARN("[%d] Error no transport for %s peer %d on channel %d", connector->comm->rank,
        type == proxyRecv ? "recv" : "send", peer, channel->id);
    return ncclInternalError;
  }
  if (connector->transportComm->proxy == NULL) return ncclSuccess;

  struct ncclProxyState* state = &connector->comm->proxyState;
  struct ncclProxyArgs* op;
  NCCLCHECK(allocateArgs(connector->comm, &op));
  memcpy(op, args, sizeof(struct ncclProxyArgs));
  op->subs[0].connector = connector;
  op->progress = connector->transportComm->proxy;
  op->state = ncclProxyOpReady;
  op->proxyAppendPtr = connector->proxyAppendPtr;

  if (state->nextOps == NULL) state->nextOps = op;
  else state->nextOpsEnd->next = op;
  state->nextOpsEnd = op;
  return ncclSuccess;
}

ncclResult_t ncclProxySaveColl(struct ncclProxyArgs* args, int pattern, int root, int nranks) {
  struct ncclChannel* channel = args->subs[0].channel;
  if (pattern == ncclPatternRing || pattern == ncclPatternRingTwice || pattern == ncclPatternPipelineFrom || pattern == ncclPatternPipelineTo) {
    struct ncclRing* ring = &channel->ring;
    if (NeedProxy(proxyRecv, pattern, root, ring, nranks)) NCCLCHECK(SaveProxy(proxyRecv, ring->prev, args, 0));
    if (NeedProxy(proxySend, pattern, root, ring, nranks)) NCCLCHECK(SaveProxy(proxySend, ring->next, args, 0));
  }
  if (pattern == ncclPatternTreeUp || pattern == ncclPatternTreeUpDown) {
    // Tree up
    struct ncclTree* tree = &channel->tree;
    for (int i=0; i<NCCL_MAX_TREE_ARITY; i++) NCCLCHECK(SaveProxy(proxyRecv, tree->down[i], args, 0));
    NCCLCHECK(SaveProxy(proxySend, tree->up, args, 0));
  }
  if (pattern == ncclPatternTreeDown || pattern == ncclPatternTreeUpDown) {
    // Tree down
    struct ncclTree* tree = &channel->tree;
    for (int i=0; i< NCCL_MAX_TREE_ARITY; i++) NCCLCHECK(SaveProxy(proxySend, tree->down[i], args, 0));
    NCCLCHECK(SaveProxy(proxyRecv, tree->up, args, 0));
  }
  if (pattern == ncclPatternCollTreeUp || pattern == ncclPatternCollTreeUpDown) {
    // CollTree up
    NCCLCHECK(SaveProxy(proxySend, channel->collTree.out, args, 1));  // For CollTree up, we are using push
  }
  if (pattern == ncclPatternCollTreeDown || pattern == ncclPatternCollTreeUpDown) {
    // CollTree down
    NCCLCHECK(SaveProxy(proxyRecv, channel->collTree.out, args, 0));
  }
  return ncclSuccess;
}

ncclResult_t ncclProxySaveP2p(struct ncclInfo* info, struct ncclChannel* channel) {
  struct ncclProxyArgs args;
  memset(&args, 0, sizeof(struct ncclProxyArgs));
  args.nsubs = 1;
  struct ncclProxySubArgs* sub = args.subs;
  sub->channel = channel;
  args.sliceSteps = 1;
  args.chunkSteps = 1;
  args.protocol = NCCL_PROTO_SIMPLE;
  args.opCount = channel->workFifoTail-1;
  args.dtype = info->datatype;

  int stepSize = info->comm->buffSizes[NCCL_PROTO_SIMPLE]/NCCL_STEPS/SENDRECV_SLICEFACTOR;
  info->recvChunkSize = stepSize;
  info->sendChunkSize = stepSize;

  if (info->delta > 0 && info->recvbytes >= 0) {
    int peerrecv = (info->comm->nRanks+info->comm->rank-info->delta)%info->comm->nRanks;
    if (channel->peers[peerrecv].recv[0].transportComm && channel->peers[peerrecv].recv[0].transportComm->proxy) {
      // Tune chunk size for the network
      if (info->recvbytes < stepSize) info->recvChunkSize /= 4;
      else if (info->recvbytes < 8*stepSize) info->recvChunkSize /= 2;
      sub->nsteps = DIVUP(info->recvbytes, info->recvChunkSize);
      if (sub->nsteps == 0) sub->nsteps = 1;
      sub->recvbytes = info->recvbytes;
      sub->sendbytes = 0;
      NCCLCHECK(SaveProxy(proxyRecv, peerrecv, &args, 0));
    }
  }
  if (info->delta > 0 && info->sendbytes >= 0) {
    int peersend = (info->comm->rank+info->delta)%info->comm->nRanks;
    if (channel->peers[peersend].send[0].transportComm && channel->peers[peersend].send[0].transportComm->proxy) {
      // Tune chunk size for the network
      if (info->sendbytes < stepSize) info->sendChunkSize /= 4;
      else if (info->sendbytes < 8*stepSize) info->sendChunkSize /= 2;
      sub->nsteps = DIVUP(info->sendbytes, info->sendChunkSize);
      if (sub->nsteps == 0) sub->nsteps = 1;
      sub->sendbytes = info->sendbytes;
      sub->recvbytes = 0;
      NCCLCHECK(SaveProxy(proxySend, peersend, &args, 0));
    }
  }
  return ncclSuccess;
}

static ncclResult_t removeOp(struct ncclProxyState* state, struct ncclProxyArgs** opPtr, struct ncclProxyArgs** prevOpPtr) {
  struct ncclProxyArgs* freeOp = *opPtr;
  DEBUG_PROXY_PRINT("Remove %ld -> %ld -> %ld\n", OP_INDEX(*prevOpPtr), OP_INDEX(freeOp), OP_INDEX(freeOp->next));
  struct ncclProxyArgs* next = freeOp->next;
  *opPtr = next;
  if (freeOp->nextPeer) {
    // replace op by nextPeer
    struct ncclProxyArgs* nextPeer = freeOp->nextPeer;
    if (*prevOpPtr) {
      (*prevOpPtr)->next = nextPeer;
    } else {
      state->ops = nextPeer;
    }
    nextPeer->next = next;
    *(prevOpPtr) = nextPeer;
  } else {
    *(freeOp->proxyAppendPtr) = NULL;
    if (*prevOpPtr) {
      (*prevOpPtr)->next = next;
    } else {
      state->ops = next;
    }
  }
  freeOp->next = NULL;
  if (state->freeList) state->freeListEnd->next = freeOp;
  else state->freeList = freeOp;
  state->freeListEnd = freeOp;
  state->freeListCount++;
  if (state->freeListCount % 32 == 0) {
    pthread_mutex_lock(&state->poolMutex);
    state->freeListEnd->next = state->pool;
    state->pool = state->freeList;
    pthread_mutex_unlock(&state->poolMutex);
    state->freeList = state->freeListEnd = NULL;
  }
  DEBUG_PROXY_PRINT("Removed %5ld (%5ld)                                               : ", OP_INDEX(freeOp), OP_INDEX(*freeOp->proxyAppendPtr));
  NCCLCHECK(dumpProxyState(state));
  return ncclSuccess;
}

static ncclResult_t progressOps(struct ncclProxyState* state, struct ncclProxyArgs** opsPtr, int* idle, struct ncclComm* comm) {
  struct ncclProxyArgs* prevOp = NULL;
  struct ncclProxyArgs* op = *opsPtr;
  while (op) {
    if (op->state == ncclProxyOpNone) return ncclInternalError;
    // opCount >= lastOpCount are part of an ongoing GroupStart/GroupEnd that hasn't started
    // yet and might be cancelled before they even start. Hold on on those.
    if (op->opCount < comm->lastOpCount) {
      if (op->state == ncclProxyOpReady) profilingRecord(op, 0);
      NCCLCHECK(op->progress(op));
      *idle &= op->idle;
    }
    if (op->state == ncclProxyOpNone) {
      profilingRecord(op, 0);
      NCCLCHECK(removeOp(state, &op, &prevOp));
    } else {
      if (op->idle == 0) profilingRecord(op, 0);
      prevOp = op;
      op = op->next;
    }
  }
  return ncclSuccess;
}

void* persistentThread(void *comm_) {
  struct ncclComm* comm = (struct ncclComm*)comm_;
  struct ncclProxyState* state = &comm->proxyState;
  char threadName[16];
  sprintf(threadName, "NCCLproxy %5d", comm->rank);
  nvtxNameOsThreadA(syscall(SYS_gettid), threadName);

  pthread_mutex_lock(&state->opsMutex);
  struct ncclProxyArgs** opsPtr = &state->ops;
  while (1) {
    if (*comm->abortFlag) {
      pthread_mutex_unlock(&state->opsMutex);
      return NULL;
    }

    while (*opsPtr == NULL) {
      if (state->stop) {
        // No more commands to process and proxy has been requested to stop
        pthread_mutex_unlock(&state->opsMutex);
        return NULL;
      }
      profilingRecord(NULL, TYPE_SLEEP);
      pthread_cond_wait(&state->cond, &state->opsMutex);
      profilingRecord(NULL, TYPE_WAKEUP);
    }
    int idle = 1;
    ncclResult_t ret = progressOps(state, opsPtr, &idle, comm);
    if (ret != ncclSuccess) {
      comm->fatalError = ret;
      INFO(NCCL_ALL,"%s:%d -> %d [Proxy Thread]", __FILE__, __LINE__, ret);
      pthread_mutex_unlock(&state->opsMutex);
      return NULL;
    }
    if (idle) {
      pthread_mutex_unlock(&state->opsMutex);
      sched_yield(); // No request progressed. Let others run.
      profilingRecord(NULL, TYPE_IDLE);
      pthread_mutex_lock(&state->opsMutex);
    }
  }
}

ncclResult_t ncclProxyStart(struct ncclComm* comm) {
  struct ncclProxyState* state = &comm->proxyState;
  pthread_mutex_lock(&state->opsMutex);
  profilingRecord(NULL, TYPE_APPEND);

  // Sort operations as we append them : sends first, then
  // receives (and collectives).
  ncclProxyArgs* next, *prev = NULL, *op = state->nextOps;
  while (op) {
    next = op->next;
    if (op->subs[0].sendbytes) {
      if (prev) prev->next = next;
      else state->nextOps = next;
      op->next = NULL;
      NCCLCHECK(ProxyAppend(state, op));
    } else prev = op;
    op = next;
  }
  op = state->nextOps;
  while (op) {
    next = op->next;
    op->next = NULL;
    NCCLCHECK(ProxyAppend(state, op));
    op = next;
  }
  state->nextOps = state->nextOpsEnd = NULL;
  NCCLCHECK(dumpProxyState(state));

  profilingRecord(NULL, TYPE_APPEND_END);
  if (state->ops != NULL)
    pthread_cond_signal(&state->cond);
  pthread_mutex_unlock(&state->opsMutex);
  return ncclSuccess;
}

ncclResult_t ncclProxySharedBuffersInit(struct ncclComm* comm, int cuda, int* size, char** ptr) {
  struct ncclProxySharedBuffers* state = &comm->proxyState.sharedBuffs;
  if (state->size == 0) {
    int p2pnChannels = 1;
    while (p2pnChannels < comm->nChannels) p2pnChannels *= 2;
    int p2pSize = 2*p2pnChannels*NCCL_MAX_WORK_ELEMENTS*comm->buffSizes[NCCL_PROTO_SIMPLE]/SENDRECV_SLICEFACTOR;
    int collNetSize = 2*comm->nChannels*comm->buffSizes[NCCL_PROTO_SIMPLE];
    state->size = std::max(p2pSize, collNetSize);
  }

  *size = state->size;

  if (cuda && state->cudaBuff == NULL) {
    NCCLCHECK(ncclCudaCalloc(&state->cudaBuff, *size));
  } else if (state->hostBuff == NULL) {
    NCCLCHECK(ncclCudaHostCalloc(&state->hostBuff, *size));
  }
  *ptr = cuda ? state->cudaBuff : state->hostBuff;
  return ncclSuccess;
}

ncclResult_t ncclProxySharedBuffersGetP2p(struct ncclComm* comm, int cuda, int type, int channel, int slot, int index, char** ptr) {
  struct ncclProxySharedBuffers* state = &comm->proxyState.sharedBuffs;
  // Use different pools for different channels and also separate send/recv.
  char* buff = cuda ? state->cudaBuff : state->hostBuff;
  int slotSize = comm->buffSizes[NCCL_PROTO_SIMPLE]/(NCCL_STEPS*SENDRECV_SLICEFACTOR);
  int globalSlot = (((type*comm->p2pnChannels+channel)*NCCL_STEPS)+slot)*NCCL_MAX_WORK_ELEMENTS+index;
  *ptr = buff + slotSize * globalSlot;
  return ncclSuccess;
}
ncclResult_t ncclProxySharedBuffersGetCollNet(struct ncclComm* comm, int cuda, int type, int channel, int slot, int index, char** ptr) {
  struct ncclProxySharedBuffers* state = &comm->proxyState.sharedBuffs;
  // Use different pools for different channels and also separate send/recv.
  char* buff = cuda ? state->cudaBuff : state->hostBuff;
  int slotSize = comm->buffSizes[NCCL_PROTO_SIMPLE]/NCCL_STEPS;
  int globalSlot = ((type*NCCL_STEPS+slot)*comm->nChannels)+channel;
  *ptr = buff + slotSize * globalSlot;
  return ncclSuccess;
}

ncclResult_t ncclProxySharedBuffersDestroy(struct ncclComm* comm) {
  struct ncclProxySharedBuffers* state = &comm->proxyState.sharedBuffs;
  CUDACHECK(cudaFree(state->cudaBuff));
  NCCLCHECK(ncclCudaHostFree(state->hostBuff));
  return ncclSuccess;
}

ncclResult_t ncclProxyCreate(struct ncclComm* comm) {
  if (!comm->proxyThread) {
    comm->proxyState.cond = PTHREAD_COND_INITIALIZER;
    comm->proxyState.opsMutex = PTHREAD_MUTEX_INITIALIZER;
    comm->proxyState.poolMutex = PTHREAD_MUTEX_INITIALIZER;
    comm->proxyState.ops = NULL;
    pthread_create(&comm->proxyThread, NULL, persistentThread, comm);
  }
  return ncclSuccess;
}

ncclResult_t ncclProxyDestroy(struct ncclComm* comm) {
  struct ncclProxyState* state = &comm->proxyState;

  // Request the proxy to stop and then wake it
  pthread_mutex_lock(&state->opsMutex);
  state->stop = true;
  pthread_cond_signal(&state->cond);
  pthread_mutex_unlock(&state->opsMutex);
  if (comm->proxyThread) pthread_join(comm->proxyThread, NULL);

  profilingDump();
  // Free off any memory allocated for the proxy arg pools
  pthread_mutex_lock(&state->poolMutex);
  struct ncclProxyState* proxyState = &comm->proxyState;
  while (proxyState->pools != NULL) {
    struct ncclProxyPool *next = proxyState->pools->next;
    free(proxyState->pools);
    proxyState->pools = next;
  }
  pthread_mutex_unlock(&state->poolMutex);

  NCCLCHECK(ncclProxySharedBuffersDestroy(comm));

  return ncclSuccess;
}
