#ifndef NCCL_DEVICE_KERNELS_H_
#define NCCL_DEVICE_KERNELS_H_
#include "nccl.h"
#include "nccl_device.h"
#include "nccl_common.h"

////////////////////////////////////////////////////////////////////////////////
// ncclDevk[Foo]: Kernels built on the device API

constexpr int ncclDevkMaxBlocks = 64;
constexpr int ncclDevkMaxThreads = 512;
constexpr int ncclDevkLLMaxEltSize = 8;

constexpr __host__ __device__ int ncclDevkLLMaxSlots(int eltSize = ncclDevkLLMaxEltSize) {
  return ncclDevkMaxThreads*ncclDevkLLMaxEltSize/eltSize;
}

struct alignas(16) ncclDevkDevArgs {
  struct ncclDevComm comm;
  int rootRank;
  uint64_t redOpArg; // must be collectively uniform
  size_t nElts;
  ncclWindow_t inputWin, outputWin;
  size_t inputOff, outputOff;
};

enum ncclDevkKernelId {
  ncclDevkKernelId_AllReduce_AGxLL_R,
  ncclDevkKernelId_AllReduce_AGxLLMC_R,
  ncclDevkKernelId_AllReduce_RSxLD_AGxST,
  ncclDevkKernelId_AllReduce_RSxLDMC_AGxSTMC,
  ncclDevkKernelId_AllReduce_RSxNet_ARxMC_AGxNet,

  ncclDevkKernelId_AllGather_LL,
  ncclDevkKernelId_AllGather_LLMC,
  ncclDevkKernelId_AllGather_ST,
  ncclDevkKernelId_AllGather_STMC,

  ncclDevkKernelId_ReduceScatter_LL,
  ncclDevkKernelId_ReduceScatter_LD,
  ncclDevkKernelId_ReduceScatter_LDMC,

  ncclDevkKernelId_Count
};

struct ncclDevkState {
  bool initialized;
  struct ncclDevComm devComm;
};

// We assume ncclComm contains a field: `ncclDevkState devkState`
ncclResult_t ncclDevkInitOnce(struct ncclComm* comm);
ncclResult_t ncclDevkFinalize(struct ncclComm* comm);

bool ncclDevkImplemented(ncclFunc_t fn, int/*ncclDevRedOp_t*/ red, ncclDataType_t ty);

ncclResult_t ncclDevkPickKernel(struct ncclComm* comm, ncclFunc_t fn, int/*ncclDevRedOp_t*/ red, ncclDataType_t ty, size_t nElts, float* estTimeUs, ncclDevkKernelId* kernelId, int* nBlocks, int* nWarps);

ncclResult_t ncclDevkMakeLaunchArgs(
  struct ncclComm* comm, struct ncclTaskColl* task, struct ncclMemoryStack* memArg,
  void** outKernelFn, void** outArg, size_t* outArgSize
);

// Generated by src/device/symmetric/generate.py
extern int const ncclDevkKernelCount;
extern void* const ncclDevkKernelList[];
void* ncclDevkGetKernelPtr(ncclDevkKernelId kernelId, int/*ncclDevRedOp_t*/ red, ncclDataType_t ty);
const char* ncclDevkKernelIdToString(int kernelId);

#endif
