#ifndef NCCL_DEVICE_KERNELS_H_
#define NCCL_DEVICE_KERNELS_H_
#include "nccl.h"
#include "nccl_device.h"
#include "nccl_common.h"
#include "device.h"

////////////////////////////////////////////////////////////////////////////////
// ncclDevk[Foo]: Kernels built on the device API

#define NCCL_DEVICE_KERNEL_CELL_SIZE 1024 // no less than 16 bytes minimal cell size

constexpr int ncclDevkMaxBlocks = 64;
constexpr int ncclDevkMaxThreads = 512;
constexpr int ncclDevkLLMaxEltSize = 8;

constexpr __host__ __device__ int ncclDevkLLMaxSlots(int eltSize = ncclDevkLLMaxEltSize) {
  return ncclDevkMaxThreads*ncclDevkLLMaxEltSize/eltSize;
}

enum ncclDevkKernelId {
  ncclDevkKernelId_AllReduce_AGxLL_R,
  ncclDevkKernelId_AllReduce_AGxLLMC_R,
  ncclDevkKernelId_AllReduce_RSxLD_AGxST,
  ncclDevkKernelId_AllReduce_RSxLDMC_AGxSTMC,
  ncclDevkKernelId_AllReduce_RSxNet_ARxMC_AGxNet,

  ncclDevkKernelId_AllGather_LL,
  ncclDevkKernelId_AllGather_LLMC,
  ncclDevkKernelId_AllGather_ST,
  ncclDevkKernelId_AllGather_STMC,

  ncclDevkKernelId_ReduceScatter_LL,
  ncclDevkKernelId_ReduceScatter_LD,
  ncclDevkKernelId_ReduceScatter_LDMC,

  ncclDevkKernelId_Count
};

struct ncclDevkState {
  bool initialized;
  struct ncclDevComm devComm;
};

struct ncclDevkChannelWorkRange {
  uint16_t workHi; // inclusive index of my ending work
  uint16_t fracHi; // 16-bit fraction in (0.0, 1.0] indicating where my part ends
};

// 16 bytes aligned
struct alignas(16) ncclDevkDevWork {
  uint64_t redOpArg; // must be collectively uniform
  size_t nElts;
  struct ncclWindow_vidmem* inputWin, *outputWin;
  size_t inputOff, outputOff; // these = origUserOffset + cbdPartOffset
  uint64_t rootRank;
  uint64_t sChannelId:16, nChannels:16, padding:32;
};

struct alignas(16) ncclDevkDevWorkArgs {
  struct ncclDevComm comm;
  int nMaxChannels;
  // starting of channelWorkRange will be aligned to 16 bytes
  // channelWorkRange[nChannels];
  // ncclSymDevWork[nWorks];
  // aux functions
  __host__ static constexpr size_t calcArgsSize(int nChannels, int nWorks) {
    return alignUp(sizeof(struct ncclDevkDevWorkArgs), 16) + alignUp(nChannels * sizeof(struct ncclDevkChannelWorkRange), 16) + nWorks * sizeof(struct ncclDevkDevWork);
  }
  __host__ __device__ struct ncclDevkChannelWorkRange* getWorkRange() const {
    return (struct ncclDevkChannelWorkRange*)((uint8_t*)this + alignUp(sizeof(struct ncclDevkDevWorkArgs), 16));
  }
  __host__ __device__ struct ncclDevkDevWork* getWorks(int nChannels) const {
    return (struct ncclDevkDevWork*)((uint8_t*)this->getWorkRange() + alignUp(nChannels * sizeof(struct ncclDevkChannelWorkRange), 16));
  }
};

union ncclDevkDevWorkArgs4K {
  struct ncclDevkDevWorkArgs args;
  char buf4K[4096];
};

// We assume ncclComm contains a field: `ncclDevkState devkState`
ncclResult_t ncclDevkInitOnce(struct ncclComm* comm);
ncclResult_t ncclDevkFinalize(struct ncclComm* comm);

bool ncclDevkImplemented(ncclFunc_t fn, int/*ncclDevRedOp_t*/ red, ncclDataType_t ty);

ncclResult_t ncclDevkPickKernel(struct ncclComm* comm, ncclFunc_t fn, int/*ncclDevRedOp_t*/ red, ncclDataType_t ty, size_t nElts, float* estTimeUs, ncclDevkKernelId* kernelId, int* nBlocks, int* nWarps);

ncclResult_t ncclDevkMakeDevWork(struct ncclComm* comm, struct ncclTaskColl* task, struct ncclDevkDevWork* outDevWork);

// Generated by src/device/symmetric/generate.py
extern int const ncclDevkKernelCount;
extern void* const ncclDevkKernelList[];
void* ncclDevkGetKernelPtr(ncclDevkKernelId kernelId, int/*ncclDevRedOp_t*/ red, ncclDataType_t ty);
const char* ncclDevkKernelIdToString(int kernelId);

#endif
